//! Edge computing model: local data processing rules, aggregation at edge,
//! threshold-based alerting, data forwarding rules, edge-cloud sync,
//! offline buffering, and edge function execution.

use std::collections::{HashMap, VecDeque};

use chrono::{DateTime, Utc};
use uuid::Uuid;

// ── Types ──

/// Comparison operator for threshold rules.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompareOp {
    GreaterThan,
    GreaterOrEqual,
    LessThan,
    LessOrEqual,
    Equal,
    NotEqual,
}

impl CompareOp {
    pub fn evaluate(&self, left: f64, right: f64) -> bool {
        match self {
            Self::GreaterThan => left > right,
            Self::GreaterOrEqual => left >= right,
            Self::LessThan => left < right,
            Self::LessOrEqual => left <= right,
            Self::Equal => (left - right).abs() < 1e-10,
            Self::NotEqual => (left - right).abs() >= 1e-10,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::GreaterThan => ">",
            Self::GreaterOrEqual => ">=",
            Self::LessThan => "<",
            Self::LessOrEqual => "<=",
            Self::Equal => "==",
            Self::NotEqual => "!=",
        }
    }
}

/// Severity level for edge alerts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

impl AlertSeverity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Warning => "warning",
            Self::Critical => "critical",
        }
    }
}

/// Aggregation function for edge data processing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AggregateFunc {
    Sum,
    Average,
    Min,
    Max,
    Count,
    Last,
}

impl AggregateFunc {
    pub fn apply(&self, values: &[f64]) -> Option<f64> {
        if values.is_empty() {
            return None;
        }
        match self {
            Self::Sum => Some(values.iter().sum()),
            Self::Average => Some(values.iter().sum::<f64>() / values.len() as f64),
            Self::Min => values.iter().cloned().reduce(f64::min),
            Self::Max => values.iter().cloned().reduce(f64::max),
            Self::Count => Some(values.len() as f64),
            Self::Last => values.last().copied(),
        }
    }
}

/// A single data record flowing through the edge pipeline.
#[derive(Debug, Clone)]
pub struct EdgeRecord {
    pub id: String,
    pub source: String,
    pub metric: String,
    pub value: f64,
    pub timestamp: DateTime<Utc>,
    pub tags: HashMap<String, String>,
}

impl EdgeRecord {
    pub fn new(source: &str, metric: &str, value: f64) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            source: source.to_string(),
            metric: metric.to_string(),
            value,
            timestamp: Utc::now(),
            tags: HashMap::new(),
        }
    }

    pub fn with_timestamp(mut self, ts: DateTime<Utc>) -> Self {
        self.timestamp = ts;
        self
    }

    pub fn with_tag(mut self, key: &str, val: &str) -> Self {
        self.tags.insert(key.to_string(), val.to_string());
        self
    }
}

/// An alert generated by edge threshold processing.
#[derive(Debug, Clone)]
pub struct Alert {
    pub id: String,
    pub rule_name: String,
    pub severity: AlertSeverity,
    pub message: String,
    pub metric: String,
    pub value: f64,
    pub threshold: f64,
    pub timestamp: DateTime<Utc>,
}

// ── Processing Rule ──

/// A rule for local data processing at the edge.
#[derive(Debug, Clone)]
pub struct ProcessingRule {
    pub name: String,
    pub metric_filter: String,
    pub transform: TransformAction,
    pub enabled: bool,
}

/// Transform action applied by a processing rule.
#[derive(Debug, Clone)]
pub enum TransformAction {
    /// Scale value by a factor.
    Scale(f64),
    /// Offset value by an amount.
    Offset(f64),
    /// Clamp value to [min, max].
    Clamp(f64, f64),
    /// Round value to given decimal places.
    Round(u32),
    /// Discard the record (filter out).
    Discard,
}

impl TransformAction {
    pub fn apply(&self, value: f64) -> Option<f64> {
        match self {
            Self::Scale(factor) => Some(value * factor),
            Self::Offset(amount) => Some(value + amount),
            Self::Clamp(min, max) => Some(value.clamp(*min, *max)),
            Self::Round(decimals) => {
                let factor = 10_f64.powi(*decimals as i32);
                Some((value * factor).round() / factor)
            }
            Self::Discard => None,
        }
    }
}

impl ProcessingRule {
    pub fn new(name: &str, metric_filter: &str, transform: TransformAction) -> Self {
        Self {
            name: name.to_string(),
            metric_filter: metric_filter.to_string(),
            transform,
            enabled: true,
        }
    }
}

// ── Threshold Alert Rule ──

/// Threshold-based alerting rule.
#[derive(Debug, Clone)]
pub struct ThresholdRule {
    pub name: String,
    pub metric: String,
    pub op: CompareOp,
    pub threshold: f64,
    pub severity: AlertSeverity,
    pub cooldown_secs: i64,
    last_fired: Option<DateTime<Utc>>,
}

impl ThresholdRule {
    pub fn new(name: &str, metric: &str, op: CompareOp, threshold: f64, severity: AlertSeverity) -> Self {
        Self {
            name: name.to_string(),
            metric: metric.to_string(),
            op,
            threshold,
            severity,
            cooldown_secs: 60,
            last_fired: None,
        }
    }

    pub fn with_cooldown(mut self, secs: i64) -> Self {
        self.cooldown_secs = secs;
        self
    }

    fn check(&mut self, record: &EdgeRecord) -> Option<Alert> {
        if record.metric != self.metric {
            return None;
        }
        if !self.op.evaluate(record.value, self.threshold) {
            return None;
        }

        // Cooldown check.
        if let Some(last) = self.last_fired {
            let elapsed = record.timestamp.signed_duration_since(last).num_seconds();
            if elapsed < self.cooldown_secs {
                return None;
            }
        }

        self.last_fired = Some(record.timestamp);

        Some(Alert {
            id: Uuid::new_v4().to_string(),
            rule_name: self.name.clone(),
            severity: self.severity,
            message: format!(
                "{} {} {} {} (value={})",
                self.metric, self.op.as_str(), self.threshold,
                self.severity.as_str(), record.value
            ),
            metric: self.metric.clone(),
            value: record.value,
            threshold: self.threshold,
            timestamp: record.timestamp,
        })
    }
}

// ── Forwarding Rule ──

/// Determines what data to forward to the cloud.
#[derive(Debug, Clone)]
pub struct ForwardingRule {
    pub name: String,
    pub metric_filter: Option<String>,
    pub min_interval_secs: i64,
    pub only_on_change: bool,
    pub change_threshold: f64,
    last_forwarded: HashMap<String, (f64, DateTime<Utc>)>,
}

impl ForwardingRule {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            metric_filter: None,
            min_interval_secs: 0,
            only_on_change: false,
            change_threshold: 0.0,
            last_forwarded: HashMap::new(),
        }
    }

    pub fn with_metric(mut self, metric: &str) -> Self {
        self.metric_filter = Some(metric.to_string());
        self
    }

    pub fn with_interval(mut self, secs: i64) -> Self {
        self.min_interval_secs = secs;
        self
    }

    pub fn with_change_detection(mut self, threshold: f64) -> Self {
        self.only_on_change = true;
        self.change_threshold = threshold;
        self
    }

    fn should_forward(&mut self, record: &EdgeRecord) -> bool {
        if let Some(filter) = &self.metric_filter {
            if record.metric != *filter {
                return false;
            }
        }

        let key = format!("{}:{}", record.source, record.metric);

        if let Some((last_val, last_time)) = self.last_forwarded.get(&key) {
            // Interval check.
            let elapsed = record.timestamp.signed_duration_since(*last_time).num_seconds();
            if elapsed < self.min_interval_secs {
                return false;
            }
            // Change detection.
            if self.only_on_change && (record.value - last_val).abs() < self.change_threshold {
                return false;
            }
        }

        self.last_forwarded.insert(key, (record.value, record.timestamp));
        true
    }
}

/// Sync status for edge-cloud communication.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncStatus {
    InSync,
    Pending,
    Offline,
    Error,
}

// ── Aggregation Window ──

/// Time-based aggregation at the edge.
#[derive(Debug, Clone)]
pub struct AggregationWindow {
    pub metric: String,
    pub func: AggregateFunc,
    pub window_secs: i64,
    buffer: Vec<(f64, DateTime<Utc>)>,
    last_emit: Option<DateTime<Utc>>,
}

impl AggregationWindow {
    pub fn new(metric: &str, func: AggregateFunc, window_secs: i64) -> Self {
        Self {
            metric: metric.to_string(),
            func,
            window_secs: window_secs.max(1),
            buffer: Vec::new(),
            last_emit: None,
        }
    }

    /// Add a value. Returns the aggregated result if the window has elapsed.
    pub fn add(&mut self, value: f64, timestamp: DateTime<Utc>) -> Option<f64> {
        self.buffer.push((value, timestamp));

        let should_emit = match self.last_emit {
            None => self.buffer.len() > 0,
            Some(last) => timestamp.signed_duration_since(last).num_seconds() >= self.window_secs,
        };

        if should_emit && !self.buffer.is_empty() {
            let values: Vec<f64> = self.buffer.iter().map(|(v, _)| *v).collect();
            let result = self.func.apply(&values);
            self.buffer.clear();
            self.last_emit = Some(timestamp);
            result
        } else {
            None
        }
    }

    pub fn pending_count(&self) -> usize {
        self.buffer.len()
    }
}

// ── Edge Compute Engine ──

/// Edge computing engine that processes data locally with rules, alerting,
/// forwarding, aggregation, and offline buffering.
pub struct EdgeEngine {
    processing_rules: Vec<ProcessingRule>,
    threshold_rules: Vec<ThresholdRule>,
    forwarding_rules: Vec<ForwardingRule>,
    aggregations: Vec<AggregationWindow>,
    alerts: Vec<Alert>,
    forward_queue: VecDeque<EdgeRecord>,
    offline_buffer: VecDeque<EdgeRecord>,
    max_offline_buffer: usize,
    sync_status: SyncStatus,
    processed_count: u64,
    forwarded_count: u64,
}

impl EdgeEngine {
    pub fn new() -> Self {
        Self {
            processing_rules: Vec::new(),
            threshold_rules: Vec::new(),
            forwarding_rules: Vec::new(),
            aggregations: Vec::new(),
            alerts: Vec::new(),
            forward_queue: VecDeque::new(),
            offline_buffer: VecDeque::new(),
            max_offline_buffer: 10_000,
            sync_status: SyncStatus::InSync,
            processed_count: 0,
            forwarded_count: 0,
        }
    }

    pub fn set_max_offline_buffer(&mut self, max: usize) {
        self.max_offline_buffer = max;
    }

    pub fn add_processing_rule(&mut self, rule: ProcessingRule) {
        self.processing_rules.push(rule);
    }

    pub fn add_threshold_rule(&mut self, rule: ThresholdRule) {
        self.threshold_rules.push(rule);
    }

    pub fn add_forwarding_rule(&mut self, rule: ForwardingRule) {
        self.forwarding_rules.push(rule);
    }

    pub fn add_aggregation(&mut self, agg: AggregationWindow) {
        self.aggregations.push(agg);
    }

    /// Process a single record through the edge pipeline.
    pub fn process(&mut self, mut record: EdgeRecord) -> ProcessResult {
        self.processed_count += 1;
        let mut result = ProcessResult {
            processed: true,
            discarded: false,
            alerts: Vec::new(),
            forwarded: false,
            aggregated: Vec::new(),
        };

        // Apply processing rules.
        for rule in &self.processing_rules {
            if !rule.enabled {
                continue;
            }
            if rule.metric_filter == record.metric || rule.metric_filter == "*" {
                match rule.transform.apply(record.value) {
                    Some(new_val) => record.value = new_val,
                    None => {
                        result.discarded = true;
                        return result;
                    }
                }
            }
        }

        // Threshold alerting.
        for rule in &mut self.threshold_rules {
            if let Some(alert) = rule.check(&record) {
                result.alerts.push(alert.clone());
                self.alerts.push(alert);
            }
        }

        // Aggregation.
        for agg in &mut self.aggregations {
            if agg.metric == record.metric {
                if let Some(agg_val) = agg.add(record.value, record.timestamp) {
                    result.aggregated.push((agg.metric.clone(), agg_val));
                }
            }
        }

        // Forwarding.
        let mut should_forward = false;
        for rule in &mut self.forwarding_rules {
            if rule.should_forward(&record) {
                should_forward = true;
                break;
            }
        }

        if should_forward {
            match self.sync_status {
                SyncStatus::InSync | SyncStatus::Pending => {
                    self.forward_queue.push_back(record);
                    self.forwarded_count += 1;
                    result.forwarded = true;
                }
                SyncStatus::Offline | SyncStatus::Error => {
                    // Buffer for later sync.
                    if self.offline_buffer.len() < self.max_offline_buffer {
                        self.offline_buffer.push_back(record);
                    }
                    self.sync_status = SyncStatus::Offline;
                }
            }
        }

        result
    }

    /// Set the sync status (simulates connectivity changes).
    pub fn set_sync_status(&mut self, status: SyncStatus) {
        let was_offline = self.sync_status == SyncStatus::Offline
            || self.sync_status == SyncStatus::Error;
        self.sync_status = status;

        // Flush offline buffer when coming back online.
        if was_offline && (status == SyncStatus::InSync || status == SyncStatus::Pending) {
            while let Some(record) = self.offline_buffer.pop_front() {
                self.forward_queue.push_back(record);
                self.forwarded_count += 1;
            }
        }
    }

    /// Drain the forward queue (simulates cloud upload).
    pub fn drain_forward_queue(&mut self) -> Vec<EdgeRecord> {
        self.forward_queue.drain(..).collect()
    }

    pub fn sync_status(&self) -> SyncStatus {
        self.sync_status
    }

    pub fn alert_count(&self) -> usize {
        self.alerts.len()
    }

    pub fn alerts(&self) -> &[Alert] {
        &self.alerts
    }

    pub fn forward_queue_len(&self) -> usize {
        self.forward_queue.len()
    }

    pub fn offline_buffer_len(&self) -> usize {
        self.offline_buffer.len()
    }

    pub fn processed_count(&self) -> u64 {
        self.processed_count
    }

    pub fn forwarded_count(&self) -> u64 {
        self.forwarded_count
    }
}

impl Default for EdgeEngine {
    fn default() -> Self {
        Self::new()
    }
}

/// Result of processing a single record.
#[derive(Debug)]
pub struct ProcessResult {
    pub processed: bool,
    pub discarded: bool,
    pub alerts: Vec<Alert>,
    pub forwarded: bool,
    pub aggregated: Vec<(String, f64)>,
}

// ── Tests ──

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;

    #[test]
    fn compare_op_evaluate() {
        assert!(CompareOp::GreaterThan.evaluate(10.0, 5.0));
        assert!(!CompareOp::GreaterThan.evaluate(5.0, 10.0));
        assert!(CompareOp::LessThan.evaluate(3.0, 7.0));
        assert!(CompareOp::Equal.evaluate(5.0, 5.0));
        assert!(CompareOp::NotEqual.evaluate(5.0, 6.0));
    }

    #[test]
    fn aggregate_func_sum() {
        assert_eq!(AggregateFunc::Sum.apply(&[1.0, 2.0, 3.0]), Some(6.0));
    }

    #[test]
    fn aggregate_func_average() {
        let avg = AggregateFunc::Average.apply(&[2.0, 4.0, 6.0]).unwrap();
        assert!((avg - 4.0).abs() < 1e-10);
    }

    #[test]
    fn aggregate_func_min_max() {
        assert_eq!(AggregateFunc::Min.apply(&[3.0, 1.0, 2.0]), Some(1.0));
        assert_eq!(AggregateFunc::Max.apply(&[3.0, 1.0, 2.0]), Some(3.0));
    }

    #[test]
    fn aggregate_func_empty() {
        assert_eq!(AggregateFunc::Sum.apply(&[]), None);
    }

    #[test]
    fn transform_scale() {
        assert_eq!(TransformAction::Scale(2.0).apply(5.0), Some(10.0));
    }

    #[test]
    fn transform_clamp() {
        assert_eq!(TransformAction::Clamp(0.0, 100.0).apply(150.0), Some(100.0));
        assert_eq!(TransformAction::Clamp(0.0, 100.0).apply(-10.0), Some(0.0));
    }

    #[test]
    fn transform_round() {
        let result = TransformAction::Round(2).apply(3.14159).unwrap();
        assert!((result - 3.14).abs() < 1e-10);
    }

    #[test]
    fn transform_discard() {
        assert_eq!(TransformAction::Discard.apply(5.0), None);
    }

    #[test]
    fn processing_rule_applies() {
        let mut engine = EdgeEngine::new();
        engine.add_processing_rule(ProcessingRule::new(
            "scale_temp", "temperature", TransformAction::Scale(1.8),
        ));
        engine.add_forwarding_rule(ForwardingRule::new("all"));
        let record = EdgeRecord::new("s1", "temperature", 100.0);
        let result = engine.process(record);
        assert!(result.forwarded);
        let forwarded = engine.drain_forward_queue();
        assert_eq!(forwarded.len(), 1);
        assert!((forwarded[0].value - 180.0).abs() < 1e-10);
    }

    #[test]
    fn processing_rule_discards() {
        let mut engine = EdgeEngine::new();
        engine.add_processing_rule(ProcessingRule::new(
            "filter_noise", "noise", TransformAction::Discard,
        ));
        let record = EdgeRecord::new("s1", "noise", 0.01);
        let result = engine.process(record);
        assert!(result.discarded);
    }

    #[test]
    fn threshold_alerting() {
        let mut engine = EdgeEngine::new();
        engine.add_threshold_rule(ThresholdRule::new(
            "high_temp", "temp", CompareOp::GreaterThan, 100.0, AlertSeverity::Critical,
        ).with_cooldown(0));
        let record = EdgeRecord::new("s1", "temp", 105.0);
        let result = engine.process(record);
        assert_eq!(result.alerts.len(), 1);
        assert_eq!(result.alerts[0].severity, AlertSeverity::Critical);
    }

    #[test]
    fn threshold_cooldown() {
        let mut engine = EdgeEngine::new();
        engine.add_threshold_rule(ThresholdRule::new(
            "high_temp", "temp", CompareOp::GreaterThan, 100.0, AlertSeverity::Warning,
        ).with_cooldown(60));

        let now = Utc::now();
        let r1 = EdgeRecord::new("s1", "temp", 105.0).with_timestamp(now);
        let result1 = engine.process(r1);
        assert_eq!(result1.alerts.len(), 1);

        let r2 = EdgeRecord::new("s1", "temp", 110.0).with_timestamp(now + Duration::seconds(10));
        let result2 = engine.process(r2);
        assert!(result2.alerts.is_empty()); // Still in cooldown.
    }

    #[test]
    fn forwarding_with_interval() {
        let mut engine = EdgeEngine::new();
        engine.add_forwarding_rule(ForwardingRule::new("throttled").with_interval(60));
        let now = Utc::now();

        let r1 = EdgeRecord::new("s1", "temp", 22.0).with_timestamp(now);
        let result1 = engine.process(r1);
        assert!(result1.forwarded);

        let r2 = EdgeRecord::new("s1", "temp", 23.0).with_timestamp(now + Duration::seconds(10));
        let result2 = engine.process(r2);
        assert!(!result2.forwarded); // Too soon.
    }

    #[test]
    fn forwarding_change_detection() {
        let mut engine = EdgeEngine::new();
        engine.add_forwarding_rule(
            ForwardingRule::new("changes")
                .with_change_detection(1.0)
        );
        let now = Utc::now();

        let r1 = EdgeRecord::new("s1", "temp", 22.0).with_timestamp(now);
        engine.process(r1); // First always forwarded.

        let r2 = EdgeRecord::new("s1", "temp", 22.3).with_timestamp(now + Duration::seconds(1));
        let result2 = engine.process(r2);
        assert!(!result2.forwarded); // Change < threshold.

        let r3 = EdgeRecord::new("s1", "temp", 24.0).with_timestamp(now + Duration::seconds(2));
        let result3 = engine.process(r3);
        assert!(result3.forwarded); // Change >= threshold.
    }

    #[test]
    fn offline_buffering() {
        let mut engine = EdgeEngine::new();
        engine.add_forwarding_rule(ForwardingRule::new("all"));
        engine.set_sync_status(SyncStatus::Offline);

        let r = EdgeRecord::new("s1", "temp", 22.0);
        engine.process(r);
        assert_eq!(engine.offline_buffer_len(), 1);
        assert_eq!(engine.forward_queue_len(), 0);
    }

    #[test]
    fn offline_buffer_flushes_on_reconnect() {
        let mut engine = EdgeEngine::new();
        engine.add_forwarding_rule(ForwardingRule::new("all"));
        engine.set_sync_status(SyncStatus::Offline);

        let r = EdgeRecord::new("s1", "temp", 22.0);
        engine.process(r);
        assert_eq!(engine.offline_buffer_len(), 1);

        engine.set_sync_status(SyncStatus::InSync);
        assert_eq!(engine.offline_buffer_len(), 0);
        assert_eq!(engine.forward_queue_len(), 1);
    }

    #[test]
    fn aggregation_window() {
        let mut agg = AggregationWindow::new("temp", AggregateFunc::Average, 10);
        let now = Utc::now();
        // First add triggers immediate emit (window just started).
        let r1 = agg.add(20.0, now);
        assert!(r1.is_some());

        // Subsequent adds within the window don't emit.
        let r2 = agg.add(22.0, now + Duration::seconds(3));
        assert!(r2.is_none());
        let r3 = agg.add(24.0, now + Duration::seconds(6));
        assert!(r3.is_none());

        // After window elapses, emit aggregation.
        let r4 = agg.add(26.0, now + Duration::seconds(12));
        assert!(r4.is_some());
    }

    #[test]
    fn edge_record_tags() {
        let r = EdgeRecord::new("s1", "temp", 22.0)
            .with_tag("unit", "celsius")
            .with_tag("location", "lab");
        assert_eq!(r.tags.len(), 2);
    }

    #[test]
    fn processed_count_tracking() {
        let mut engine = EdgeEngine::new();
        for _ in 0..5 {
            engine.process(EdgeRecord::new("s1", "temp", 22.0));
        }
        assert_eq!(engine.processed_count(), 5);
    }

    #[test]
    fn drain_forward_queue() {
        let mut engine = EdgeEngine::new();
        engine.add_forwarding_rule(ForwardingRule::new("all"));
        for i in 0..3 {
            let r = EdgeRecord::new("s1", "temp", i as f64)
                .with_timestamp(Utc::now() + Duration::seconds(i));
            engine.process(r);
        }
        let drained = engine.drain_forward_queue();
        assert_eq!(drained.len(), 3);
        assert_eq!(engine.forward_queue_len(), 0);
    }
}
