//! Entity replication system for networked games — dirty tracking & priority.
//!
//! Provides `ReplicatedEntity` with id and component map, `ReplicationManager`
//! tracking entity ownership and dirty flags, serialization of only changed
//! components, replication priority (important entities replicate first),
//! ownership transfer, create/destroy replication events, component-level
//! dirty tracking, and bandwidth budget distribution across entities.

use std::collections::{HashMap, HashSet};
use std::fmt;

// ── Errors ──────────────────────────────────────────────────────

/// Replication domain errors.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReplicationError {
    /// Entity not found.
    EntityNotFound(u64),
    /// Entity already exists.
    DuplicateEntity(u64),
    /// Not the owner of this entity.
    NotOwner { entity_id: u64, owner: u64, requester: u64 },
    /// Bandwidth budget exceeded.
    BudgetExceeded { budget: usize, required: usize },
    /// Component not found on entity.
    ComponentNotFound { entity_id: u64, component: String },
}

impl fmt::Display for ReplicationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EntityNotFound(id) => write!(f, "entity not found: {id}"),
            Self::DuplicateEntity(id) => write!(f, "duplicate entity: {id}"),
            Self::NotOwner { entity_id, owner, requester } => {
                write!(f, "entity {entity_id}: owner={owner}, requester={requester}")
            }
            Self::BudgetExceeded { budget, required } => {
                write!(f, "budget exceeded: budget={budget}, required={required}")
            }
            Self::ComponentNotFound { entity_id, component } => {
                write!(f, "component '{component}' not found on entity {entity_id}")
            }
        }
    }
}

impl std::error::Error for ReplicationError {}

// ── Replication Priority ────────────────────────────────────────

/// How often an entity should be replicated relative to others.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ReplicationPriority {
    /// Replicate every cycle.
    Critical,
    /// Replicate frequently.
    High,
    /// Default replication rate.
    Normal,
    /// Replicate infrequently.
    Low,
}

impl ReplicationPriority {
    /// Weight for bandwidth allocation (higher = more bandwidth).
    pub fn weight(&self) -> u32 {
        match self {
            Self::Critical => 8,
            Self::High => 4,
            Self::Normal => 2,
            Self::Low => 1,
        }
    }
}

impl fmt::Display for ReplicationPriority {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Self::Critical => "critical",
            Self::High => "high",
            Self::Normal => "normal",
            Self::Low => "low",
        };
        write!(f, "{s}")
    }
}

// ── Replication Event ───────────────────────────────────────────

/// Events generated by the replication system.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReplicationEvent {
    /// A new entity was created.
    Create { entity_id: u64, owner: u64 },
    /// An entity was destroyed.
    Destroy { entity_id: u64 },
    /// Components on an entity were updated.
    Update { entity_id: u64, components: Vec<String> },
    /// Ownership transferred.
    OwnershipTransfer { entity_id: u64, from: u64, to: u64 },
}

impl fmt::Display for ReplicationEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Create { entity_id, owner } => {
                write!(f, "Create(entity={entity_id}, owner={owner})")
            }
            Self::Destroy { entity_id } => write!(f, "Destroy(entity={entity_id})"),
            Self::Update { entity_id, components } => {
                write!(f, "Update(entity={entity_id}, components={})", components.len())
            }
            Self::OwnershipTransfer { entity_id, from, to } => {
                write!(f, "Transfer(entity={entity_id}, {from}->{to})")
            }
        }
    }
}

// ── Replicated Entity ───────────────────────────────────────────

/// An entity with named components (key-value byte blobs).
#[derive(Debug, Clone)]
pub struct ReplicatedEntity {
    pub id: u64,
    pub owner: u64,
    pub priority: ReplicationPriority,
    components: HashMap<String, Vec<u8>>,
    dirty: HashSet<String>,
}

impl ReplicatedEntity {
    pub fn new(id: u64, owner: u64) -> Self {
        Self {
            id,
            owner,
            priority: ReplicationPriority::Normal,
            components: HashMap::new(),
            dirty: HashSet::new(),
        }
    }

    pub fn with_priority(mut self, p: ReplicationPriority) -> Self {
        self.priority = p;
        self
    }

    /// Set a component value and mark it dirty.
    pub fn set_component(&mut self, name: impl Into<String>, data: Vec<u8>) {
        let n = name.into();
        self.components.insert(n.clone(), data);
        self.dirty.insert(n);
    }

    /// Get a component value.
    pub fn get_component(&self, name: &str) -> Option<&Vec<u8>> {
        self.components.get(name)
    }

    /// Remove a component.
    pub fn remove_component(&mut self, name: &str) -> Option<Vec<u8>> {
        self.dirty.remove(name);
        self.components.remove(name)
    }

    /// Components that have been modified since last clear.
    pub fn dirty_components(&self) -> &HashSet<String> {
        &self.dirty
    }

    /// Clear dirty flags.
    pub fn clear_dirty(&mut self) {
        self.dirty.clear();
    }

    /// Is any component dirty?
    pub fn is_dirty(&self) -> bool {
        !self.dirty.is_empty()
    }

    /// Total byte size of all components.
    pub fn byte_size(&self) -> usize {
        self.components.values().map(|v| v.len()).sum::<usize>()
            + self.components.keys().map(|k| k.len()).sum::<usize>()
    }

    /// Byte size of dirty components only.
    pub fn dirty_byte_size(&self) -> usize {
        self.dirty.iter()
            .filter_map(|k| self.components.get(k).map(|v| k.len() + v.len()))
            .sum()
    }

    /// Number of components.
    pub fn component_count(&self) -> usize {
        self.components.len()
    }

    /// Component names.
    pub fn component_names(&self) -> Vec<String> {
        self.components.keys().cloned().collect()
    }
}

impl fmt::Display for ReplicatedEntity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "ReplicatedEntity(id={}, owner={}, pri={}, comps={}, dirty={})",
            self.id, self.owner, self.priority, self.components.len(), self.dirty.len(),
        )
    }
}

// ── Replication Manager ─────────────────────────────────────────

/// Manages entity replication: ownership, dirty tracking, events, bandwidth.
pub struct ReplicationManager {
    entities: HashMap<u64, ReplicatedEntity>,
    /// Pending events to be sent.
    pending_events: Vec<ReplicationEvent>,
    /// Bandwidth budget per replication cycle (bytes).
    bandwidth_budget: usize,
    /// Statistics.
    total_bytes_replicated: u64,
    total_updates_sent: u64,
}

impl ReplicationManager {
    pub fn new(bandwidth_budget: usize) -> Self {
        Self {
            entities: HashMap::new(),
            pending_events: Vec::new(),
            bandwidth_budget,
            total_bytes_replicated: 0,
            total_updates_sent: 0,
        }
    }

    /// Register a new entity for replication.
    pub fn create_entity(&mut self, entity: ReplicatedEntity) -> Result<(), ReplicationError> {
        if self.entities.contains_key(&entity.id) {
            return Err(ReplicationError::DuplicateEntity(entity.id));
        }
        let id = entity.id;
        let owner = entity.owner;
        self.entities.insert(id, entity);
        self.pending_events.push(ReplicationEvent::Create { entity_id: id, owner });
        Ok(())
    }

    /// Destroy a replicated entity.
    pub fn destroy_entity(&mut self, id: u64) -> Result<ReplicatedEntity, ReplicationError> {
        let entity = self.entities.remove(&id)
            .ok_or(ReplicationError::EntityNotFound(id))?;
        self.pending_events.push(ReplicationEvent::Destroy { entity_id: id });
        Ok(entity)
    }

    /// Get an entity by ID.
    pub fn get_entity(&self, id: u64) -> Option<&ReplicatedEntity> {
        self.entities.get(&id)
    }

    /// Get a mutable entity reference.
    pub fn get_entity_mut(&mut self, id: u64) -> Option<&mut ReplicatedEntity> {
        self.entities.get_mut(&id)
    }

    /// Set a component on an entity (must be owner).
    pub fn set_component(
        &mut self,
        entity_id: u64,
        requester: u64,
        component: impl Into<String>,
        data: Vec<u8>,
    ) -> Result<(), ReplicationError> {
        let entity = self.entities.get_mut(&entity_id)
            .ok_or(ReplicationError::EntityNotFound(entity_id))?;
        if entity.owner != requester {
            return Err(ReplicationError::NotOwner {
                entity_id,
                owner: entity.owner,
                requester,
            });
        }
        entity.set_component(component, data);
        Ok(())
    }

    /// Transfer ownership of an entity.
    pub fn transfer_ownership(
        &mut self,
        entity_id: u64,
        from: u64,
        to: u64,
    ) -> Result<(), ReplicationError> {
        let entity = self.entities.get_mut(&entity_id)
            .ok_or(ReplicationError::EntityNotFound(entity_id))?;
        if entity.owner != from {
            return Err(ReplicationError::NotOwner {
                entity_id,
                owner: entity.owner,
                requester: from,
            });
        }
        entity.owner = to;
        self.pending_events.push(ReplicationEvent::OwnershipTransfer {
            entity_id, from, to,
        });
        Ok(())
    }

    /// Collect dirty entities, allocate bandwidth by priority, produce update events.
    pub fn replicate(&mut self) -> Vec<ReplicationEvent> {
        let mut events = std::mem::take(&mut self.pending_events);
        let mut budget_remaining = self.bandwidth_budget;

        // Collect dirty entities sorted by priority (Critical first).
        let mut dirty_ids: Vec<(u64, ReplicationPriority, usize)> = self.entities.iter()
            .filter(|(_, e)| e.is_dirty())
            .map(|(&id, e)| (id, e.priority, e.dirty_byte_size()))
            .collect();
        dirty_ids.sort_by(|a, b| a.1.cmp(&b.1));

        for (id, _pri, size) in dirty_ids {
            if size > budget_remaining {
                continue;
            }
            budget_remaining -= size;

            if let Some(entity) = self.entities.get_mut(&id) {
                let comp_names: Vec<String> = entity.dirty_components().iter().cloned().collect();
                entity.clear_dirty();
                self.total_bytes_replicated += size as u64;
                self.total_updates_sent += 1;
                events.push(ReplicationEvent::Update {
                    entity_id: id,
                    components: comp_names,
                });
            }
        }

        events
    }

    /// Drain pending events without running replication.
    pub fn drain_events(&mut self) -> Vec<ReplicationEvent> {
        std::mem::take(&mut self.pending_events)
    }

    /// Number of entities.
    pub fn entity_count(&self) -> usize {
        self.entities.len()
    }

    /// Number of dirty entities.
    pub fn dirty_count(&self) -> usize {
        self.entities.values().filter(|e| e.is_dirty()).count()
    }

    /// Get all entity IDs owned by a given peer.
    pub fn entities_owned_by(&self, owner: u64) -> Vec<u64> {
        self.entities.iter()
            .filter(|(_, e)| e.owner == owner)
            .map(|(&id, _)| id)
            .collect()
    }

    /// Total bytes replicated across all cycles.
    pub fn total_bytes_replicated(&self) -> u64 {
        self.total_bytes_replicated
    }

    /// Total update events sent.
    pub fn total_updates_sent(&self) -> u64 {
        self.total_updates_sent
    }

    /// Bandwidth budget.
    pub fn bandwidth_budget(&self) -> usize {
        self.bandwidth_budget
    }

    /// Set bandwidth budget.
    pub fn set_bandwidth_budget(&mut self, budget: usize) {
        self.bandwidth_budget = budget;
    }
}

impl fmt::Display for ReplicationManager {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "ReplicationManager(entities={}, dirty={}, budget={}B)",
            self.entities.len(),
            self.dirty_count(),
            self.bandwidth_budget,
        )
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entity_set_and_get_component() {
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("pos", vec![1, 2, 3]);
        assert_eq!(e.get_component("pos"), Some(&vec![1, 2, 3]));
    }

    #[test]
    fn entity_dirty_tracking() {
        let mut e = ReplicatedEntity::new(1, 100);
        assert!(!e.is_dirty());
        e.set_component("hp", vec![100]);
        assert!(e.is_dirty());
        assert!(e.dirty_components().contains("hp"));
        e.clear_dirty();
        assert!(!e.is_dirty());
    }

    #[test]
    fn entity_remove_component() {
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("x", vec![1]);
        assert_eq!(e.remove_component("x"), Some(vec![1]));
        assert!(e.get_component("x").is_none());
    }

    #[test]
    fn entity_byte_size() {
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("ab", vec![1, 2, 3]);
        assert_eq!(e.byte_size(), 5); // 2 + 3
    }

    #[test]
    fn entity_priority_weight() {
        assert!(ReplicationPriority::Critical.weight() > ReplicationPriority::High.weight());
        assert!(ReplicationPriority::High.weight() > ReplicationPriority::Normal.weight());
        assert!(ReplicationPriority::Normal.weight() > ReplicationPriority::Low.weight());
    }

    #[test]
    fn entity_display() {
        let e = ReplicatedEntity::new(1, 100);
        let d = format!("{e}");
        assert!(d.contains("ReplicatedEntity"));
    }

    #[test]
    fn manager_create_entity() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        assert_eq!(mgr.entity_count(), 1);
    }

    #[test]
    fn manager_create_duplicate_error() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        assert!(matches!(
            mgr.create_entity(ReplicatedEntity::new(1, 200)),
            Err(ReplicationError::DuplicateEntity(1))
        ));
    }

    #[test]
    fn manager_destroy_entity() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        mgr.destroy_entity(1).unwrap();
        assert_eq!(mgr.entity_count(), 0);
    }

    #[test]
    fn manager_set_component_owner_check() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        mgr.set_component(1, 100, "pos", vec![1]).unwrap();
        assert!(matches!(
            mgr.set_component(1, 999, "pos", vec![2]),
            Err(ReplicationError::NotOwner { .. })
        ));
    }

    #[test]
    fn manager_transfer_ownership() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        mgr.transfer_ownership(1, 100, 200).unwrap();
        assert_eq!(mgr.get_entity(1).unwrap().owner, 200);
    }

    #[test]
    fn manager_transfer_not_owner_error() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        assert!(matches!(
            mgr.transfer_ownership(1, 999, 200),
            Err(ReplicationError::NotOwner { .. })
        ));
    }

    #[test]
    fn manager_replicate_produces_events() {
        let mut mgr = ReplicationManager::new(10240);
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("pos", vec![1, 2]);
        mgr.create_entity(e).unwrap();
        let events = mgr.replicate();
        assert!(events.iter().any(|ev| matches!(ev, ReplicationEvent::Create { .. })));
        assert!(events.iter().any(|ev| matches!(ev, ReplicationEvent::Update { .. })));
    }

    #[test]
    fn manager_replicate_clears_dirty() {
        let mut mgr = ReplicationManager::new(10240);
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("x", vec![1]);
        mgr.create_entity(e).unwrap();
        mgr.replicate();
        assert_eq!(mgr.dirty_count(), 0);
    }

    #[test]
    fn manager_bandwidth_budget_limits() {
        let mut mgr = ReplicationManager::new(5); // tiny budget
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("big", vec![0; 100]);
        mgr.create_entity(e).unwrap();
        let events = mgr.replicate();
        // The update event should be skipped (too large for budget).
        assert!(!events.iter().any(|ev| matches!(ev, ReplicationEvent::Update { .. })));
    }

    #[test]
    fn manager_entities_owned_by() {
        let mut mgr = ReplicationManager::new(1024);
        mgr.create_entity(ReplicatedEntity::new(1, 100)).unwrap();
        mgr.create_entity(ReplicatedEntity::new(2, 100)).unwrap();
        mgr.create_entity(ReplicatedEntity::new(3, 200)).unwrap();
        assert_eq!(mgr.entities_owned_by(100).len(), 2);
    }

    #[test]
    fn manager_stats() {
        let mut mgr = ReplicationManager::new(10240);
        let mut e = ReplicatedEntity::new(1, 100);
        e.set_component("a", vec![1]);
        mgr.create_entity(e).unwrap();
        mgr.replicate();
        assert!(mgr.total_bytes_replicated() > 0);
        assert_eq!(mgr.total_updates_sent(), 1);
    }

    #[test]
    fn replication_event_display() {
        let e = ReplicationEvent::Create { entity_id: 1, owner: 2 };
        assert!(format!("{e}").contains("Create"));
    }

    #[test]
    fn priority_display() {
        assert_eq!(format!("{}", ReplicationPriority::Critical), "critical");
    }

    #[test]
    fn manager_display() {
        let mgr = ReplicationManager::new(1024);
        let d = format!("{mgr}");
        assert!(d.contains("ReplicationManager"));
    }
}
