//! Event emitter — typed events, on/off/once, wildcard listeners, event
//! bubbling, max listeners, error events, and async-style emit.
//!
//! Pure-Rust event system inspired by Node.js EventEmitter but with
//! type-safe, synchronous dispatch. No real async runtime required.

use std::collections::HashMap;
use std::fmt;

// ── Listener ID ────────────────────────────────────────────────────

/// Unique identifier for a registered listener.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ListenerId(u64);

impl fmt::Display for ListenerId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Listener({})", self.0)
    }
}

// ── Event data ─────────────────────────────────────────────────────

/// An event carrying a type name and payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Event {
    pub event_type: String,
    pub data: String,
    /// Whether propagation has been stopped.
    stopped: bool,
    /// Whether the default action has been prevented.
    default_prevented: bool,
}

impl Event {
    pub fn new(event_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self {
            event_type: event_type.into(),
            data: data.into(),
            stopped: false,
            default_prevented: false,
        }
    }

    pub fn stop_propagation(&mut self) {
        self.stopped = true;
    }

    pub fn is_propagation_stopped(&self) -> bool {
        self.stopped
    }

    pub fn prevent_default(&mut self) {
        self.default_prevented = true;
    }

    pub fn is_default_prevented(&self) -> bool {
        self.default_prevented
    }
}

// ── Listener types ─────────────────────────────────────────────────

/// How a listener was registered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ListenerKind {
    /// Persistent listener (on).
    On,
    /// One-shot listener (once).
    Once,
}

/// A registered listener.
#[derive(Debug)]
struct Listener {
    id: ListenerId,
    kind: ListenerKind,
    /// Priority (higher = called first). Default is 0.
    priority: i32,
}

// ── Emit result ────────────────────────────────────────────────────

/// Result of emitting an event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmitResult {
    /// Number of listeners that were called.
    pub listener_count: usize,
    /// Whether propagation was stopped by a listener.
    pub propagation_stopped: bool,
    /// Whether default was prevented by a listener.
    pub default_prevented: bool,
}

// ── Captured events ────────────────────────────────────────────────

/// A captured event with listener ID (used instead of closures for testability).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CapturedEvent {
    pub listener_id: ListenerId,
    pub event: Event,
}

// ── Emitter configuration ──────────────────────────────────────────

/// Configuration for the event emitter.
#[derive(Debug, Clone)]
pub struct EmitterConfig {
    /// Maximum listeners per event type (0 = unlimited).
    pub max_listeners: usize,
    /// Whether to enable wildcard (*) listeners.
    pub enable_wildcard: bool,
    /// Whether to emit error events when max listeners exceeded.
    pub warn_on_max_listeners: bool,
}

impl Default for EmitterConfig {
    fn default() -> Self {
        Self {
            max_listeners: 10,
            enable_wildcard: true,
            warn_on_max_listeners: true,
        }
    }
}

// ── Event emitter ──────────────────────────────────────────────────

/// A synchronous event emitter with typed events, wildcard support, and priority.
#[derive(Debug)]
pub struct EventEmitter {
    config: EmitterConfig,
    /// Listeners per event type. The special key "*" matches all events.
    listeners: HashMap<String, Vec<Listener>>,
    next_id: u64,
    /// Events captured during emit (since we can't use closures, we capture here).
    captured: Vec<CapturedEvent>,
    /// Error events generated by the emitter itself.
    errors: Vec<String>,
}

impl EventEmitter {
    pub fn new(config: EmitterConfig) -> Self {
        Self {
            config,
            listeners: HashMap::new(),
            next_id: 1,
            captured: Vec::new(),
            errors: Vec::new(),
        }
    }

    /// Register a persistent listener for an event type. Returns the listener ID.
    pub fn on(&mut self, event_type: impl Into<String>, priority: i32) -> ListenerId {
        self.add_listener(event_type.into(), ListenerKind::On, priority)
    }

    /// Register a one-shot listener for an event type. Returns the listener ID.
    pub fn once(&mut self, event_type: impl Into<String>, priority: i32) -> ListenerId {
        self.add_listener(event_type.into(), ListenerKind::Once, priority)
    }

    /// Register a wildcard listener that receives all events.
    pub fn on_any(&mut self, priority: i32) -> ListenerId {
        self.add_listener("*".to_string(), ListenerKind::On, priority)
    }

    fn add_listener(&mut self, event_type: String, kind: ListenerKind, priority: i32) -> ListenerId {
        let id = ListenerId(self.next_id);
        self.next_id += 1;

        let list = self.listeners.entry(event_type.clone()).or_default();

        // Check max listeners
        if self.config.max_listeners > 0 && list.len() >= self.config.max_listeners {
            if self.config.warn_on_max_listeners {
                self.errors.push(format!(
                    "max listeners ({}) exceeded for event type: {}",
                    self.config.max_listeners, event_type
                ));
            }
        }

        list.push(Listener { id, kind, priority });
        // Sort by priority descending (higher priority first)
        list.sort_by(|a, b| b.priority.cmp(&a.priority));
        id
    }

    /// Remove a listener by ID. Returns true if found and removed.
    pub fn off(&mut self, listener_id: ListenerId) -> bool {
        for listeners in self.listeners.values_mut() {
            let before = listeners.len();
            listeners.retain(|l| l.id != listener_id);
            if listeners.len() < before {
                return true;
            }
        }
        false
    }

    /// Remove all listeners for a specific event type.
    pub fn remove_all_listeners(&mut self, event_type: &str) {
        self.listeners.remove(event_type);
    }

    /// Remove all listeners.
    pub fn remove_all(&mut self) {
        self.listeners.clear();
    }

    /// Emit an event. Calls all matching listeners (including wildcards).
    pub fn emit(&mut self, event: Event) -> EmitResult {
        let mut count = 0;

        // Collect listener IDs and their priorities for the specific event type
        let mut to_call: Vec<(ListenerId, i32)> = Vec::new();
        if let Some(listeners) = self.listeners.get(&event.event_type) {
            for l in listeners {
                to_call.push((l.id, l.priority));
            }
        }

        // Collect wildcard listeners
        if self.config.enable_wildcard && event.event_type != "*" {
            if let Some(wildcards) = self.listeners.get("*") {
                for l in wildcards {
                    to_call.push((l.id, l.priority));
                }
            }
        }

        // Sort all by priority descending
        to_call.sort_by(|a, b| b.1.cmp(&a.1));

        // Dispatch
        let mut once_ids = Vec::new();
        for (lid, _) in &to_call {
            if event.is_propagation_stopped() {
                break;
            }
            // Check if this listener still exists (may have been removed during emit)
            let mut found = false;
            let mut is_once = false;
            for listeners in self.listeners.values() {
                if let Some(l) = listeners.iter().find(|l| l.id == *lid) {
                    found = true;
                    is_once = l.kind == ListenerKind::Once;
                    break;
                }
            }
            if !found {
                continue;
            }
            self.captured.push(CapturedEvent {
                listener_id: *lid,
                event: event.clone(),
            });
            count += 1;
            if is_once {
                once_ids.push(*lid);
            }
        }

        // Remove once listeners
        for id in once_ids {
            self.off(id);
        }

        EmitResult {
            listener_count: count,
            propagation_stopped: event.is_propagation_stopped(),
            default_prevented: event.is_default_prevented(),
        }
    }

    /// Take all captured events since last call.
    pub fn take_captured(&mut self) -> Vec<CapturedEvent> {
        std::mem::take(&mut self.captured)
    }

    /// Take all error messages since last call.
    pub fn take_errors(&mut self) -> Vec<String> {
        std::mem::take(&mut self.errors)
    }

    /// Number of listeners for a specific event type.
    pub fn listener_count(&self, event_type: &str) -> usize {
        self.listeners.get(event_type).map_or(0, |l| l.len())
    }

    /// Total number of listeners across all event types.
    pub fn total_listener_count(&self) -> usize {
        self.listeners.values().map(|l| l.len()).sum()
    }

    /// List all event types that have listeners.
    pub fn event_types(&self) -> Vec<&str> {
        let mut types: Vec<&str> = self.listeners.keys()
            .filter(|k| !self.listeners[*k].is_empty())
            .map(|k| k.as_str())
            .collect();
        types.sort();
        types
    }

    /// Check if a specific listener is registered.
    pub fn has_listener(&self, listener_id: ListenerId) -> bool {
        self.listeners.values().any(|list| list.iter().any(|l| l.id == listener_id))
    }
}

impl Default for EventEmitter {
    fn default() -> Self {
        Self::new(EmitterConfig::default())
    }
}

// ── Event bubbling ─────────────────────────────────────────────────

/// An event target that can participate in event bubbling (parent-child hierarchy).
#[derive(Debug)]
pub struct EventTarget {
    pub name: String,
    emitter: EventEmitter,
    children: Vec<String>,
}

impl EventTarget {
    pub fn new(name: impl Into<String>, config: EmitterConfig) -> Self {
        Self {
            name: name.into(),
            emitter: EventEmitter::new(config),
            children: Vec::new(),
        }
    }

    pub fn emitter(&mut self) -> &mut EventEmitter {
        &mut self.emitter
    }

    pub fn add_child(&mut self, child_name: impl Into<String>) {
        self.children.push(child_name.into());
    }

    pub fn children(&self) -> &[String] {
        &self.children
    }
}

/// A tree of event targets for bubbling simulation.
#[derive(Debug, Default)]
pub struct EventBubbleTree {
    targets: HashMap<String, EventTarget>,
    /// child_name -> parent_name
    parent_map: HashMap<String, String>,
}

impl EventBubbleTree {
    pub fn new() -> Self {
        Self {
            targets: HashMap::new(),
            parent_map: HashMap::new(),
        }
    }

    pub fn add_target(&mut self, target: EventTarget) {
        self.targets.insert(target.name.clone(), target);
    }

    pub fn set_parent(&mut self, child: &str, parent: &str) {
        self.parent_map.insert(child.to_string(), parent.to_string());
        if let Some(p) = self.targets.get_mut(parent) {
            if !p.children.contains(&child.to_string()) {
                p.children.push(child.to_string());
            }
        }
    }

    pub fn get_target(&mut self, name: &str) -> Option<&mut EventTarget> {
        self.targets.get_mut(name)
    }

    /// Emit an event on a target and bubble up to ancestors.
    /// Returns the list of targets the event was dispatched on.
    pub fn emit_with_bubbling(&mut self, target_name: &str, event: Event) -> Vec<String> {
        let mut path = Vec::new();
        let mut current = target_name.to_string();
        let evt = event;

        loop {
            if evt.is_propagation_stopped() {
                break;
            }
            if let Some(target) = self.targets.get_mut(&current) {
                target.emitter.emit(evt.clone());
                path.push(current.clone());
            } else {
                break;
            }
            // Find parent
            if let Some(parent) = self.parent_map.get(&current) {
                current = parent.clone();
            } else {
                break;
            }
        }

        path
    }
}

// ── Tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn emitter() -> EventEmitter {
        EventEmitter::new(EmitterConfig {
            max_listeners: 10,
            enable_wildcard: true,
            warn_on_max_listeners: true,
        })
    }

    // ── ListenerId ─────────────────────────────────────────────────

    #[test]
    fn listener_id_display() {
        let id = ListenerId(42);
        assert_eq!(id.to_string(), "Listener(42)");
    }

    // ── Event ──────────────────────────────────────────────────────

    #[test]
    fn event_creation() {
        let e = Event::new("click", r#"{"x":10}"#);
        assert_eq!(e.event_type, "click");
        assert_eq!(e.data, r#"{"x":10}"#);
        assert!(!e.is_propagation_stopped());
        assert!(!e.is_default_prevented());
    }

    #[test]
    fn event_stop_propagation() {
        let mut e = Event::new("click", "");
        e.stop_propagation();
        assert!(e.is_propagation_stopped());
    }

    #[test]
    fn event_prevent_default() {
        let mut e = Event::new("submit", "");
        e.prevent_default();
        assert!(e.is_default_prevented());
    }

    // ── on / emit ──────────────────────────────────────────────────

    #[test]
    fn on_and_emit() {
        let mut em = emitter();
        let id = em.on("click", 0);
        assert!(em.has_listener(id));

        let result = em.emit(Event::new("click", "data"));
        assert_eq!(result.listener_count, 1);

        let captured = em.take_captured();
        assert_eq!(captured.len(), 1);
        assert_eq!(captured[0].listener_id, id);
        assert_eq!(captured[0].event.event_type, "click");
    }

    #[test]
    fn emit_no_listeners() {
        let mut em = emitter();
        let result = em.emit(Event::new("click", ""));
        assert_eq!(result.listener_count, 0);
    }

    #[test]
    fn on_persistent() {
        let mut em = emitter();
        em.on("click", 0);

        em.emit(Event::new("click", "1"));
        em.emit(Event::new("click", "2"));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 2);
    }

    // ── once ───────────────────────────────────────────────────────

    #[test]
    fn once_fires_once() {
        let mut em = emitter();
        let id = em.once("click", 0);

        em.emit(Event::new("click", "1"));
        assert!(!em.has_listener(id)); // removed after first emit

        em.emit(Event::new("click", "2"));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 1); // only first
    }

    // ── off ────────────────────────────────────────────────────────

    #[test]
    fn off_removes_listener() {
        let mut em = emitter();
        let id = em.on("click", 0);
        assert!(em.off(id));
        assert!(!em.has_listener(id));
        assert!(!em.off(id)); // already removed
    }

    #[test]
    fn remove_all_listeners_for_type() {
        let mut em = emitter();
        em.on("click", 0);
        em.on("click", 0);
        em.on("hover", 0);
        em.remove_all_listeners("click");
        assert_eq!(em.listener_count("click"), 0);
        assert_eq!(em.listener_count("hover"), 1);
    }

    #[test]
    fn remove_all() {
        let mut em = emitter();
        em.on("a", 0);
        em.on("b", 0);
        em.remove_all();
        assert_eq!(em.total_listener_count(), 0);
    }

    // ── Wildcard ───────────────────────────────────────────────────

    #[test]
    fn wildcard_listener() {
        let mut em = emitter();
        em.on_any(0);

        em.emit(Event::new("click", ""));
        em.emit(Event::new("hover", ""));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 2);
    }

    #[test]
    fn wildcard_disabled() {
        let mut em = EventEmitter::new(EmitterConfig {
            enable_wildcard: false,
            ..Default::default()
        });
        em.on_any(0);

        em.emit(Event::new("click", ""));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 0); // wildcard not triggered
    }

    // ── Priority ───────────────────────────────────────────────────

    #[test]
    fn priority_ordering() {
        let mut em = emitter();
        let low = em.on("click", 0);
        let high = em.on("click", 10);

        em.emit(Event::new("click", ""));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 2);
        // High priority should be first
        assert_eq!(captured[0].listener_id, high);
        assert_eq!(captured[1].listener_id, low);
    }

    // ── Propagation stop ───────────────────────────────────────────

    #[test]
    fn stop_propagation_in_emit() {
        let mut em = emitter();
        em.on("click", 10); // high priority
        em.on("click", 0);  // low priority

        let mut event = Event::new("click", "");
        event.stop_propagation();
        let result = em.emit(event);
        assert_eq!(result.listener_count, 0); // propagation stopped before any listener
        assert!(result.propagation_stopped);
    }

    // ── Max listeners warning ──────────────────────────────────────

    #[test]
    fn max_listeners_warning() {
        let mut em = EventEmitter::new(EmitterConfig {
            max_listeners: 2,
            warn_on_max_listeners: true,
            ..Default::default()
        });
        em.on("click", 0);
        em.on("click", 0);
        em.on("click", 0); // exceeds max
        let errors = em.take_errors();
        assert_eq!(errors.len(), 1);
        assert!(errors[0].contains("max listeners"));
    }

    #[test]
    fn max_listeners_no_warning() {
        let mut em = EventEmitter::new(EmitterConfig {
            max_listeners: 2,
            warn_on_max_listeners: false,
            ..Default::default()
        });
        em.on("click", 0);
        em.on("click", 0);
        em.on("click", 0);
        assert!(em.take_errors().is_empty());
    }

    #[test]
    fn unlimited_listeners() {
        let mut em = EventEmitter::new(EmitterConfig {
            max_listeners: 0,
            ..Default::default()
        });
        for _ in 0..100 {
            em.on("click", 0);
        }
        assert_eq!(em.listener_count("click"), 100);
        assert!(em.take_errors().is_empty());
    }

    // ── Counting and listing ───────────────────────────────────────

    #[test]
    fn listener_count() {
        let mut em = emitter();
        em.on("a", 0);
        em.on("a", 0);
        em.on("b", 0);
        assert_eq!(em.listener_count("a"), 2);
        assert_eq!(em.listener_count("b"), 1);
        assert_eq!(em.listener_count("c"), 0);
        assert_eq!(em.total_listener_count(), 3);
    }

    #[test]
    fn event_types_list() {
        let mut em = emitter();
        em.on("click", 0);
        em.on("hover", 0);
        let types = em.event_types();
        assert_eq!(types, vec!["click", "hover"]);
    }

    // ── Default ────────────────────────────────────────────────────

    #[test]
    fn default_emitter() {
        let em = EventEmitter::default();
        assert_eq!(em.total_listener_count(), 0);
    }

    // ── Event bubbling ─────────────────────────────────────────────

    #[test]
    fn bubble_up() {
        let mut tree = EventBubbleTree::new();
        tree.add_target(EventTarget::new("child", EmitterConfig::default()));
        tree.add_target(EventTarget::new("parent", EmitterConfig::default()));
        tree.add_target(EventTarget::new("root", EmitterConfig::default()));
        tree.set_parent("child", "parent");
        tree.set_parent("parent", "root");

        // Add listeners at each level
        tree.get_target("child").unwrap().emitter().on("click", 0);
        tree.get_target("parent").unwrap().emitter().on("click", 0);
        tree.get_target("root").unwrap().emitter().on("click", 0);

        let path = tree.emit_with_bubbling("child", Event::new("click", ""));
        assert_eq!(path, vec!["child", "parent", "root"]);
    }

    #[test]
    fn bubble_stopped() {
        let mut tree = EventBubbleTree::new();
        tree.add_target(EventTarget::new("child", EmitterConfig::default()));
        tree.add_target(EventTarget::new("parent", EmitterConfig::default()));
        tree.set_parent("child", "parent");

        tree.get_target("child").unwrap().emitter().on("click", 0);
        tree.get_target("parent").unwrap().emitter().on("click", 0);

        let mut event = Event::new("click", "");
        event.stop_propagation();
        let path = tree.emit_with_bubbling("child", event);
        assert!(path.is_empty()); // stopped immediately
    }

    #[test]
    fn bubble_unknown_target() {
        let mut tree = EventBubbleTree::new();
        let path = tree.emit_with_bubbling("ghost", Event::new("click", ""));
        assert!(path.is_empty());
    }

    #[test]
    fn bubble_no_parent() {
        let mut tree = EventBubbleTree::new();
        tree.add_target(EventTarget::new("leaf", EmitterConfig::default()));
        tree.get_target("leaf").unwrap().emitter().on("click", 0);

        let path = tree.emit_with_bubbling("leaf", Event::new("click", ""));
        assert_eq!(path, vec!["leaf"]);
    }

    // ── Mixed listeners ────────────────────────────────────────────

    #[test]
    fn mixed_on_and_once() {
        let mut em = emitter();
        em.on("click", 0);
        em.once("click", 0);

        em.emit(Event::new("click", "1"));
        assert_eq!(em.listener_count("click"), 1); // once removed

        em.emit(Event::new("click", "2"));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 3); // 2 from first emit, 1 from second
    }

    #[test]
    fn wildcard_with_specific() {
        let mut em = emitter();
        let specific = em.on("click", 0);
        let wildcard = em.on_any(0);

        em.emit(Event::new("click", ""));
        let captured = em.take_captured();
        assert_eq!(captured.len(), 2);
        let ids: Vec<ListenerId> = captured.iter().map(|c| c.listener_id).collect();
        assert!(ids.contains(&specific));
        assert!(ids.contains(&wildcard));
    }
}
