//! Local Trajectory Planner — trajectory rollout with cost evaluation, dynamic
//! obstacle integration, velocity command generation, and trajectory scoring.
//!
//! Given a robot's current pose and velocity, the local planner samples a space
//! of feasible (v, ω) commands, forward-simulates each candidate trajectory,
//! scores them against multiple cost functions (goal heading, obstacle
//! clearance, path alignment, velocity preference), and selects the
//! highest-scoring trajectory.

use std::fmt;

// ── Errors ──────────────────────────────────────────────────────

/// Local planner errors.
#[derive(Debug, Clone, PartialEq)]
pub enum LocalPlannerError {
    /// No feasible trajectory found.
    NoFeasible,
    /// Invalid parameter.
    InvalidParam(String),
    /// Collision detected on all candidates.
    AllColliding,
}

impl fmt::Display for LocalPlannerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoFeasible => write!(f, "no feasible trajectory"),
            Self::InvalidParam(m) => write!(f, "invalid parameter: {m}"),
            Self::AllColliding => write!(f, "all candidate trajectories collide"),
        }
    }
}

impl std::error::Error for LocalPlannerError {}

// ── 2-D Pose ────────────────────────────────────────────────────

/// 2-D pose: x, y position and heading θ (radians).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Pose2D {
    pub x: f64,
    pub y: f64,
    pub theta: f64,
}

impl Pose2D {
    pub fn new(x: f64, y: f64, theta: f64) -> Self {
        Self { x, y, theta }
    }

    /// Distance to another point.
    pub fn distance_to(&self, other: &Pose2D) -> f64 {
        let dx = self.x - other.x;
        let dy = self.y - other.y;
        (dx * dx + dy * dy).sqrt()
    }
}

impl fmt::Display for Pose2D {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Pose({:.2}, {:.2}, θ={:.3})", self.x, self.y, self.theta)
    }
}

// ── Velocity Command ────────────────────────────────────────────

/// Velocity command: linear velocity v (m/s) and angular velocity ω (rad/s).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VelCmd {
    pub v: f64,
    pub omega: f64,
}

impl VelCmd {
    pub fn new(v: f64, omega: f64) -> Self {
        Self { v, omega }
    }

    pub fn zero() -> Self {
        Self { v: 0.0, omega: 0.0 }
    }
}

impl fmt::Display for VelCmd {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Vel(v={:.3}, ω={:.3})", self.v, self.omega)
    }
}

// ── Dynamic Obstacle ────────────────────────────────────────────

/// A circular dynamic obstacle with position and velocity.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DynamicObstacle {
    pub x: f64,
    pub y: f64,
    pub vx: f64,
    pub vy: f64,
    pub radius: f64,
}

impl DynamicObstacle {
    pub fn new(x: f64, y: f64, radius: f64) -> Self {
        Self { x, y, vx: 0.0, vy: 0.0, radius }
    }

    pub fn with_velocity(mut self, vx: f64, vy: f64) -> Self {
        self.vx = vx;
        self.vy = vy;
        self
    }

    /// Predict position at time `t` seconds in the future.
    pub fn predict(&self, t: f64) -> (f64, f64) {
        (self.x + self.vx * t, self.y + self.vy * t)
    }
}

impl fmt::Display for DynamicObstacle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Obstacle({:.1},{:.1} r={:.2})", self.x, self.y, self.radius)
    }
}

// ── Trajectory ──────────────────────────────────────────────────

/// A candidate trajectory: a sequence of poses generated by a constant command.
#[derive(Debug, Clone)]
pub struct Trajectory {
    pub cmd: VelCmd,
    pub poses: Vec<Pose2D>,
    pub score: f64,
    pub collides: bool,
}

impl Trajectory {
    fn new(cmd: VelCmd) -> Self {
        Self { cmd, poses: Vec::new(), score: 0.0, collides: false }
    }
}

impl fmt::Display for Trajectory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Trajectory({}, pts={}, score={:.3}, coll={})",
            self.cmd,
            self.poses.len(),
            self.score,
            self.collides
        )
    }
}

// ── Cost Weights ────────────────────────────────────────────────

/// Weights for the multi-objective trajectory cost function.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CostWeights {
    /// Weight for goal heading alignment.
    pub goal_heading: f64,
    /// Weight for obstacle clearance.
    pub obstacle_clearance: f64,
    /// Weight for alignment with the global path.
    pub path_alignment: f64,
    /// Weight for preferring higher forward velocity.
    pub velocity_pref: f64,
}

impl Default for CostWeights {
    fn default() -> Self {
        Self {
            goal_heading: 1.0,
            obstacle_clearance: 2.0,
            path_alignment: 0.8,
            velocity_pref: 0.5,
        }
    }
}

// ── Velocity Limits ─────────────────────────────────────────────

/// Dynamic window: feasible velocity ranges.
#[derive(Debug, Clone, Copy)]
pub struct VelocityLimits {
    pub v_min: f64,
    pub v_max: f64,
    pub omega_min: f64,
    pub omega_max: f64,
    pub acc_v: f64,
    pub acc_omega: f64,
}

impl VelocityLimits {
    pub fn new(v_max: f64, omega_max: f64) -> Self {
        Self {
            v_min: 0.0,
            v_max,
            omega_min: -omega_max,
            omega_max,
            acc_v: 1.0,
            acc_omega: 3.0,
        }
    }

    pub fn with_acceleration(mut self, acc_v: f64, acc_omega: f64) -> Self {
        self.acc_v = acc_v;
        self.acc_omega = acc_omega;
        self
    }

    pub fn with_reverse(mut self, v_min: f64) -> Self {
        self.v_min = v_min;
        self
    }

    /// Compute the dynamic window centred on the current velocity.
    fn dynamic_window(&self, cur: VelCmd, dt: f64) -> (f64, f64, f64, f64) {
        let v_lo = (cur.v - self.acc_v * dt).max(self.v_min);
        let v_hi = (cur.v + self.acc_v * dt).min(self.v_max);
        let w_lo = (cur.omega - self.acc_omega * dt).max(self.omega_min);
        let w_hi = (cur.omega + self.acc_omega * dt).min(self.omega_max);
        (v_lo, v_hi, w_lo, w_hi)
    }
}

// ── Local Planner ───────────────────────────────────────────────

/// Trajectory-rollout local planner (Dynamic Window Approach variant).
#[derive(Debug, Clone)]
pub struct LocalPlanner {
    limits: VelocityLimits,
    weights: CostWeights,
    sim_time: f64,
    sim_dt: f64,
    v_samples: usize,
    omega_samples: usize,
    robot_radius: f64,
}

impl LocalPlanner {
    pub fn new(limits: VelocityLimits) -> Self {
        Self {
            limits,
            weights: CostWeights::default(),
            sim_time: 2.0,
            sim_dt: 0.1,
            v_samples: 10,
            omega_samples: 20,
            robot_radius: 0.3,
        }
    }

    pub fn with_weights(mut self, w: CostWeights) -> Self {
        self.weights = w;
        self
    }

    pub fn with_sim_time(mut self, t: f64) -> Self {
        self.sim_time = t.max(0.1);
        self
    }

    pub fn with_sim_dt(mut self, dt: f64) -> Self {
        self.sim_dt = dt.max(0.001);
        self
    }

    pub fn with_samples(mut self, v_samples: usize, omega_samples: usize) -> Self {
        self.v_samples = v_samples.max(2);
        self.omega_samples = omega_samples.max(2);
        self
    }

    pub fn with_robot_radius(mut self, r: f64) -> Self {
        self.robot_radius = r.max(0.0);
        self
    }

    /// Generate the best velocity command given current state.
    pub fn compute_velocity(
        &self,
        pose: Pose2D,
        cur_vel: VelCmd,
        goal: Pose2D,
        obstacles: &[DynamicObstacle],
        global_path: &[(f64, f64)],
    ) -> Result<VelCmd, LocalPlannerError> {
        let trajectories = self.sample_trajectories(pose, cur_vel, goal, obstacles, global_path);
        let best = trajectories
            .iter()
            .filter(|t| !t.collides)
            .max_by(|a, b| a.score.partial_cmp(&b.score).unwrap_or(std::cmp::Ordering::Equal));
        match best {
            Some(t) => Ok(t.cmd),
            None => {
                if trajectories.iter().all(|t| t.collides) {
                    Err(LocalPlannerError::AllColliding)
                } else {
                    Err(LocalPlannerError::NoFeasible)
                }
            }
        }
    }

    /// Sample and score candidate trajectories.
    pub fn sample_trajectories(
        &self,
        pose: Pose2D,
        cur_vel: VelCmd,
        goal: Pose2D,
        obstacles: &[DynamicObstacle],
        global_path: &[(f64, f64)],
    ) -> Vec<Trajectory> {
        let (v_lo, v_hi, w_lo, w_hi) = self.limits.dynamic_window(cur_vel, self.sim_dt);
        let dv = if self.v_samples > 1 {
            (v_hi - v_lo) / (self.v_samples - 1) as f64
        } else {
            0.0
        };
        let dw = if self.omega_samples > 1 {
            (w_hi - w_lo) / (self.omega_samples - 1) as f64
        } else {
            0.0
        };

        let mut trajectories = Vec::new();
        for vi in 0..self.v_samples {
            let v = v_lo + vi as f64 * dv;
            for wi in 0..self.omega_samples {
                let omega = w_lo + wi as f64 * dw;
                let cmd = VelCmd::new(v, omega);
                let mut traj = self.rollout(pose, cmd);
                self.check_collisions(&mut traj, obstacles);
                if !traj.collides {
                    traj.score = self.score(&traj, goal, obstacles, global_path);
                }
                trajectories.push(traj);
            }
        }
        trajectories
    }

    /// Forward-simulate a constant velocity command.
    fn rollout(&self, start: Pose2D, cmd: VelCmd) -> Trajectory {
        let mut traj = Trajectory::new(cmd);
        let mut p = start;
        traj.poses.push(p);
        let steps = (self.sim_time / self.sim_dt).ceil() as usize;
        for _ in 0..steps {
            let new_theta = p.theta + cmd.omega * self.sim_dt;
            let new_x = p.x + cmd.v * new_theta.cos() * self.sim_dt;
            let new_y = p.y + cmd.v * new_theta.sin() * self.sim_dt;
            p = Pose2D::new(new_x, new_y, new_theta);
            traj.poses.push(p);
        }
        traj
    }

    /// Check if any pose on the trajectory collides with dynamic obstacles.
    fn check_collisions(&self, traj: &mut Trajectory, obstacles: &[DynamicObstacle]) {
        for (i, pose) in traj.poses.iter().enumerate() {
            let t = i as f64 * self.sim_dt;
            for obs in obstacles {
                let (ox, oy) = obs.predict(t);
                let dx = pose.x - ox;
                let dy = pose.y - oy;
                let dist = (dx * dx + dy * dy).sqrt();
                if dist < self.robot_radius + obs.radius {
                    traj.collides = true;
                    return;
                }
            }
        }
    }

    /// Multi-objective scoring.
    fn score(
        &self,
        traj: &Trajectory,
        goal: Pose2D,
        obstacles: &[DynamicObstacle],
        global_path: &[(f64, f64)],
    ) -> f64 {
        let end = traj.poses.last().copied().unwrap_or(Pose2D::new(0.0, 0.0, 0.0));

        // Goal heading alignment: cos of angle to goal from endpoint.
        let to_goal = (goal.y - end.y).atan2(goal.x - end.x);
        let heading_score = (to_goal - end.theta).cos();

        // Minimum obstacle clearance over the trajectory.
        let clearance = self.min_clearance(traj, obstacles);
        let clearance_score = (clearance / 3.0).min(1.0);

        // Path alignment: minimum distance from endpoint to global path.
        let path_score = if global_path.is_empty() {
            0.0
        } else {
            let min_dist = global_path
                .iter()
                .map(|&(px, py)| {
                    let dx = end.x - px;
                    let dy = end.y - py;
                    (dx * dx + dy * dy).sqrt()
                })
                .fold(f64::INFINITY, f64::min);
            (1.0 - min_dist / 5.0).max(0.0)
        };

        // Velocity preference: reward forward motion.
        let vel_score = traj.cmd.v / self.limits.v_max.max(0.001);

        self.weights.goal_heading * heading_score
            + self.weights.obstacle_clearance * clearance_score
            + self.weights.path_alignment * path_score
            + self.weights.velocity_pref * vel_score
    }

    fn min_clearance(&self, traj: &Trajectory, obstacles: &[DynamicObstacle]) -> f64 {
        let mut min_d = f64::INFINITY;
        for (i, pose) in traj.poses.iter().enumerate() {
            let t = i as f64 * self.sim_dt;
            for obs in obstacles {
                let (ox, oy) = obs.predict(t);
                let dx = pose.x - ox;
                let dy = pose.y - oy;
                let d = (dx * dx + dy * dy).sqrt() - self.robot_radius - obs.radius;
                if d < min_d {
                    min_d = d;
                }
            }
        }
        min_d.max(0.0)
    }
}

impl fmt::Display for LocalPlanner {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "LocalPlanner(v_max={:.1}, sim_t={:.1}s, samples={}x{})",
            self.limits.v_max, self.sim_time, self.v_samples, self.omega_samples
        )
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn basic_planner() -> LocalPlanner {
        let limits = VelocityLimits::new(1.0, 1.5);
        LocalPlanner::new(limits).with_samples(5, 10).with_sim_time(1.0)
    }

    #[test]
    fn test_pose_distance() {
        let a = Pose2D::new(0.0, 0.0, 0.0);
        let b = Pose2D::new(3.0, 4.0, 0.0);
        assert!((a.distance_to(&b) - 5.0).abs() < 1e-9);
    }

    #[test]
    fn test_pose_display() {
        let p = Pose2D::new(1.5, 2.3, 0.1);
        let s = format!("{p}");
        assert!(s.contains("1.50"));
    }

    #[test]
    fn test_vel_cmd_zero() {
        let v = VelCmd::zero();
        assert_eq!(v.v, 0.0);
        assert_eq!(v.omega, 0.0);
    }

    #[test]
    fn test_obstacle_predict() {
        let obs = DynamicObstacle::new(1.0, 0.0, 0.5).with_velocity(2.0, 0.0);
        let (px, py) = obs.predict(1.0);
        assert!((px - 3.0).abs() < 1e-9);
        assert!((py - 0.0).abs() < 1e-9);
    }

    #[test]
    fn test_rollout_straight() {
        let planner = basic_planner();
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let cmd = VelCmd::new(1.0, 0.0);
        let traj = planner.rollout(pose, cmd);
        assert!(traj.poses.len() > 1);
        let last = traj.poses.last().unwrap();
        assert!(last.x > 0.0);
        assert!(last.y.abs() < 0.01);
    }

    #[test]
    fn test_rollout_turn() {
        let planner = basic_planner();
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let cmd = VelCmd::new(1.0, 1.0);
        let traj = planner.rollout(pose, cmd);
        let last = traj.poses.last().unwrap();
        assert!(last.theta.abs() > 0.1);
    }

    #[test]
    fn test_no_obstacles() {
        let planner = basic_planner();
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let result = planner.compute_velocity(pose, VelCmd::zero(), goal, &[], &[]);
        assert!(result.is_ok());
        let cmd = result.unwrap();
        assert!(cmd.v > 0.0); // should move towards goal
    }

    #[test]
    fn test_obstacle_avoidance() {
        let planner = basic_planner().with_robot_radius(0.3);
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let obs = vec![DynamicObstacle::new(0.6, 0.0, 0.3)];
        let result = planner.compute_velocity(pose, VelCmd::zero(), goal, &obs, &[]);
        // Either finds a path around or returns AllColliding
        if let Ok(cmd) = result {
            assert!(cmd.omega.abs() > 0.001 || cmd.v > 0.0);
        }
    }

    #[test]
    fn test_dynamic_window() {
        let limits = VelocityLimits::new(2.0, 3.0).with_acceleration(1.0, 2.0);
        let cur = VelCmd::new(1.0, 0.0);
        let (v_lo, v_hi, w_lo, w_hi) = limits.dynamic_window(cur, 0.1);
        assert!(v_lo <= 1.0 && v_hi >= 1.0);
        assert!(w_lo <= 0.0 && w_hi >= 0.0);
    }

    #[test]
    fn test_with_global_path() {
        let planner = basic_planner();
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let path = vec![(1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0)];
        let result = planner.compute_velocity(pose, VelCmd::zero(), goal, &[], &path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_sample_trajectories_count() {
        let planner = basic_planner();
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let trajs = planner.sample_trajectories(pose, VelCmd::zero(), goal, &[], &[]);
        assert_eq!(trajs.len(), 5 * 10);
    }

    #[test]
    fn test_all_colliding() {
        let planner = basic_planner().with_robot_radius(5.0);
        let pose = Pose2D::new(0.0, 0.0, 0.0);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let obs = vec![DynamicObstacle::new(0.5, 0.0, 5.0)];
        let result = planner.compute_velocity(pose, VelCmd::zero(), goal, &obs, &[]);
        assert!(result.is_err());
    }

    #[test]
    fn test_reverse_velocity() {
        let limits = VelocityLimits::new(1.0, 1.5).with_reverse(-0.5);
        let planner = LocalPlanner::new(limits).with_samples(5, 5);
        let pose = Pose2D::new(0.0, 0.0, std::f64::consts::PI);
        let goal = Pose2D::new(5.0, 0.0, 0.0);
        let result = planner.compute_velocity(pose, VelCmd::zero(), goal, &[], &[]);
        assert!(result.is_ok());
    }

    #[test]
    fn test_display_local_planner() {
        let p = basic_planner();
        let s = format!("{p}");
        assert!(s.contains("LocalPlanner"));
    }

    #[test]
    fn test_velocity_limits_window_clamping() {
        let limits = VelocityLimits::new(1.0, 1.0);
        let cur = VelCmd::new(0.9, 0.9);
        let (_, v_hi, _, w_hi) = limits.dynamic_window(cur, 10.0);
        assert!(v_hi <= 1.0 + 1e-9);
        assert!(w_hi <= 1.0 + 1e-9);
    }

    #[test]
    fn test_trajectory_display() {
        let t = Trajectory { cmd: VelCmd::new(1.0, 0.5), poses: vec![], score: 0.75, collides: false };
        let s = format!("{t}");
        assert!(s.contains("0.750"));
    }

    #[test]
    fn test_obstacle_display() {
        let obs = DynamicObstacle::new(1.0, 2.0, 0.5);
        let s = format!("{obs}");
        assert!(s.contains("1.0"));
    }

    #[test]
    fn test_cost_weights_default() {
        let w = CostWeights::default();
        assert!(w.obstacle_clearance > w.goal_heading);
    }
}
