//! Market Order — market order execution, slippage estimation, partial
//! fills, price impact analysis, and notional tracking.
//!
//! Pure-Rust market order representation with fill simulation against
//! a price ladder, slippage calculation relative to a reference price,
//! and partial-fill lifecycle management.

use std::fmt;

// ── Errors ──────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub enum MarketOrderError {
    InvalidQuantity(String),
    InsufficientLiquidity(String),
    AlreadyTerminal(u64),
    EmptyLadder,
    NegativeSlippage(String),
}

impl fmt::Display for MarketOrderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidQuantity(s) => write!(f, "invalid quantity: {s}"),
            Self::InsufficientLiquidity(s) => write!(f, "insufficient liquidity: {s}"),
            Self::AlreadyTerminal(id) => write!(f, "order {id} is already terminal"),
            Self::EmptyLadder => write!(f, "price ladder is empty"),
            Self::NegativeSlippage(s) => write!(f, "negative slippage: {s}"),
        }
    }
}

impl std::error::Error for MarketOrderError {}

// ── MarketSide ──────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MarketSide {
    Buy,
    Sell,
}

impl fmt::Display for MarketSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Buy => write!(f, "MKT-BUY"),
            Self::Sell => write!(f, "MKT-SELL"),
        }
    }
}

// ── MarketOrderStatus ───────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MarketOrderStatus {
    New,
    PartiallyFilled,
    Filled,
    Rejected,
}

impl MarketOrderStatus {
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Filled | Self::Rejected)
    }
}

impl fmt::Display for MarketOrderStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::New => write!(f, "NEW"),
            Self::PartiallyFilled => write!(f, "PARTIAL"),
            Self::Filled => write!(f, "FILLED"),
            Self::Rejected => write!(f, "REJECTED"),
        }
    }
}

// ── PriceLadderLevel ────────────────────────────────────────────

/// A single level in the opposing price ladder used for fill simulation.
#[derive(Debug, Clone, PartialEq)]
pub struct PriceLadderLevel {
    pub price: f64,
    pub available: f64,
}

impl PriceLadderLevel {
    pub fn new(price: f64, available: f64) -> Self { Self { price, available } }
}

impl fmt::Display for PriceLadderLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Level({:.2} x {:.4})", self.price, self.available)
    }
}

// ── MarketFill ──────────────────────────────────────────────────

/// A fill generated by walking the price ladder.
#[derive(Debug, Clone, PartialEq)]
pub struct MarketFill {
    pub level_price: f64,
    pub quantity: f64,
    pub cumulative_qty: f64,
}

impl MarketFill {
    pub fn notional(&self) -> f64 { self.level_price * self.quantity }
}

impl fmt::Display for MarketFill {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MarketFill({:.4}@{:.2}, cum={:.4})",
            self.quantity, self.level_price, self.cumulative_qty)
    }
}

// ── FillResult ──────────────────────────────────────────────────

/// Outcome of a market order fill simulation.
#[derive(Debug, Clone)]
pub struct FillResult {
    pub fills: Vec<MarketFill>,
    pub total_filled: f64,
    pub unfilled: f64,
    pub avg_price: f64,
    pub total_notional: f64,
    pub slippage_bps: f64,
    pub levels_consumed: usize,
    pub vwap: f64,
}

impl fmt::Display for FillResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FillResult(filled={:.4}, avg={:.4}, slippage={:.1}bps, levels={})",
            self.total_filled, self.avg_price, self.slippage_bps, self.levels_consumed)
    }
}

// ── SlippageEstimate ────────────────────────────────────────────

/// Pre-trade slippage estimate for a given order size.
#[derive(Debug, Clone)]
pub struct SlippageEstimate {
    pub estimated_avg_price: f64,
    pub reference_price: f64,
    pub slippage_abs: f64,
    pub slippage_bps: f64,
    pub can_fill: bool,
    pub fillable_quantity: f64,
}

impl fmt::Display for SlippageEstimate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Slippage(est_avg={:.4}, ref={:.4}, bps={:.1}, can_fill={})",
            self.estimated_avg_price, self.reference_price, self.slippage_bps, self.can_fill)
    }
}

// ── MarketOrder ─────────────────────────────────────────────────

/// A market order that consumes liquidity across price levels.
#[derive(Debug, Clone)]
pub struct MarketOrder {
    pub order_id: u64,
    pub side: MarketSide,
    pub quantity: f64,
    pub remaining: f64,
    pub status: MarketOrderStatus,
    pub created_ns: u64,
    pub client_order_id: Option<String>,
    pub max_slippage_bps: Option<f64>,
    pub fills: Vec<MarketFill>,
}

impl MarketOrder {
    pub fn new(order_id: u64, side: MarketSide, quantity: f64) -> Self {
        Self {
            order_id,
            side,
            quantity,
            remaining: quantity,
            status: MarketOrderStatus::New,
            created_ns: 0,
            client_order_id: None,
            max_slippage_bps: None,
            fills: Vec::new(),
        }
    }

    pub fn with_created_ns(mut self, ts: u64) -> Self {
        self.created_ns = ts;
        self
    }

    pub fn with_client_order_id(mut self, id: &str) -> Self {
        self.client_order_id = Some(id.to_string());
        self
    }

    pub fn with_max_slippage_bps(mut self, bps: f64) -> Self {
        self.max_slippage_bps = Some(bps);
        self
    }

    /// Validate the order.
    pub fn validate(&self) -> Result<(), MarketOrderError> {
        if self.quantity <= 0.0 {
            return Err(MarketOrderError::InvalidQuantity(format!("{}", self.quantity)));
        }
        Ok(())
    }

    /// Simulate filling against a price ladder.
    pub fn simulate_fill(&self, ladder: &[PriceLadderLevel], ref_price: f64)
        -> Result<FillResult, MarketOrderError>
    {
        if ladder.is_empty() {
            return Err(MarketOrderError::EmptyLadder);
        }
        let mut fills = Vec::new();
        let mut remaining = self.quantity;
        let mut total_notional = 0.0;
        let mut cumulative = 0.0;
        let mut levels_used = 0;

        for level in ladder {
            if remaining <= 1e-12 { break; }
            let take = remaining.min(level.available);
            cumulative += take;
            total_notional += take * level.price;
            fills.push(MarketFill {
                level_price: level.price,
                quantity: take,
                cumulative_qty: cumulative,
            });
            remaining -= take;
            levels_used += 1;
        }

        let total_filled = self.quantity - remaining;
        let avg = if total_filled > 1e-12 { total_notional / total_filled } else { 0.0 };
        let slippage_bps = if ref_price.abs() > 1e-12 {
            ((avg - ref_price).abs() / ref_price) * 10_000.0
        } else {
            0.0
        };

        Ok(FillResult {
            fills,
            total_filled,
            unfilled: remaining,
            avg_price: avg,
            total_notional,
            slippage_bps,
            levels_consumed: levels_used,
            vwap: avg,
        })
    }

    /// Execute fills from a simulation result.
    pub fn execute(&mut self, result: &FillResult) -> Result<(), MarketOrderError> {
        if self.status.is_terminal() {
            return Err(MarketOrderError::AlreadyTerminal(self.order_id));
        }
        if let Some(max_bps) = self.max_slippage_bps {
            if result.slippage_bps > max_bps {
                self.status = MarketOrderStatus::Rejected;
                return Err(MarketOrderError::NegativeSlippage(
                    format!("slippage {:.1}bps exceeds max {:.1}bps",
                        result.slippage_bps, max_bps)));
            }
        }
        self.remaining -= result.total_filled;
        if self.remaining < 1e-12 { self.remaining = 0.0; }
        self.fills.extend(result.fills.iter().cloned());
        self.status = if self.remaining <= 1e-12 {
            MarketOrderStatus::Filled
        } else {
            MarketOrderStatus::PartiallyFilled
        };
        Ok(())
    }

    /// Estimate slippage without executing.
    pub fn estimate_slippage(&self, ladder: &[PriceLadderLevel], ref_price: f64)
        -> Result<SlippageEstimate, MarketOrderError>
    {
        let result = self.simulate_fill(ladder, ref_price)?;
        let slippage_abs = (result.avg_price - ref_price).abs();
        Ok(SlippageEstimate {
            estimated_avg_price: result.avg_price,
            reference_price: ref_price,
            slippage_abs,
            slippage_bps: result.slippage_bps,
            can_fill: result.unfilled < 1e-12,
            fillable_quantity: result.total_filled,
        })
    }

    /// Filled quantity.
    pub fn filled_quantity(&self) -> f64 { self.quantity - self.remaining }

    /// Fill ratio.
    pub fn fill_ratio(&self) -> f64 {
        if self.quantity <= 0.0 { 0.0 } else { self.filled_quantity() / self.quantity }
    }

    /// Average fill price.
    pub fn avg_fill_price(&self) -> Option<f64> {
        let total_n: f64 = self.fills.iter().map(|f| f.notional()).sum();
        let total_q: f64 = self.fills.iter().map(|f| f.quantity).sum();
        if total_q > 1e-12 { Some(total_n / total_q) } else { None }
    }

    /// Price impact: difference between worst fill and best fill.
    pub fn price_impact(&self) -> Option<f64> {
        if self.fills.len() < 2 { return None; }
        let prices: Vec<f64> = self.fills.iter().map(|f| f.level_price).collect();
        let min = prices.iter().cloned().fold(f64::INFINITY, f64::min);
        let max = prices.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        Some(max - min)
    }
}

impl fmt::Display for MarketOrder {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MarketOrder(id={}, {} qty={:.4}, status={}, filled={:.4})",
            self.order_id, self.side, self.quantity, self.status, self.filled_quantity())
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_ladder() -> Vec<PriceLadderLevel> {
        vec![
            PriceLadderLevel::new(100.0, 50.0),
            PriceLadderLevel::new(100.5, 30.0),
            PriceLadderLevel::new(101.0, 100.0),
        ]
    }

    #[test]
    fn test_new_market_order() {
        let o = MarketOrder::new(1, MarketSide::Buy, 100.0);
        assert_eq!(o.status, MarketOrderStatus::New);
        assert_eq!(o.remaining, 100.0);
    }

    #[test]
    fn test_validate_good() {
        let o = MarketOrder::new(1, MarketSide::Buy, 100.0);
        assert!(o.validate().is_ok());
    }

    #[test]
    fn test_validate_bad_qty() {
        let o = MarketOrder::new(1, MarketSide::Buy, 0.0);
        assert!(o.validate().is_err());
    }

    #[test]
    fn test_simulate_fill_single_level() {
        let o = MarketOrder::new(1, MarketSide::Buy, 30.0);
        let ladder = sample_ladder();
        let result = o.simulate_fill(&ladder, 100.0).unwrap();
        assert!((result.total_filled - 30.0).abs() < 1e-6);
        assert_eq!(result.levels_consumed, 1);
        assert!((result.avg_price - 100.0).abs() < 1e-6);
    }

    #[test]
    fn test_simulate_fill_multi_level() {
        let o = MarketOrder::new(1, MarketSide::Buy, 70.0);
        let ladder = sample_ladder();
        let result = o.simulate_fill(&ladder, 100.0).unwrap();
        assert!((result.total_filled - 70.0).abs() < 1e-6);
        assert_eq!(result.levels_consumed, 2);
        // 50@100 + 20@100.5 = 7010 / 70 = 100.1428...
        assert!(result.avg_price > 100.0);
    }

    #[test]
    fn test_simulate_fill_partial() {
        let o = MarketOrder::new(1, MarketSide::Buy, 200.0);
        let ladder = sample_ladder();
        let result = o.simulate_fill(&ladder, 100.0).unwrap();
        assert!((result.total_filled - 180.0).abs() < 1e-6);
        assert!((result.unfilled - 20.0).abs() < 1e-6);
    }

    #[test]
    fn test_simulate_empty_ladder() {
        let o = MarketOrder::new(1, MarketSide::Buy, 50.0);
        assert!(o.simulate_fill(&[], 100.0).is_err());
    }

    #[test]
    fn test_execute() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 50.0);
        let result = o.simulate_fill(&sample_ladder(), 100.0).unwrap();
        o.execute(&result).unwrap();
        assert_eq!(o.status, MarketOrderStatus::Filled);
        assert!(o.remaining < 1e-12);
    }

    #[test]
    fn test_execute_partial() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 200.0);
        let result = o.simulate_fill(&sample_ladder(), 100.0).unwrap();
        o.execute(&result).unwrap();
        assert_eq!(o.status, MarketOrderStatus::PartiallyFilled);
    }

    #[test]
    fn test_max_slippage_reject() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 100.0)
            .with_max_slippage_bps(1.0);
        let ladder = vec![
            PriceLadderLevel::new(100.0, 10.0),
            PriceLadderLevel::new(110.0, 100.0),
        ];
        let result = o.simulate_fill(&ladder, 100.0).unwrap();
        assert!(o.execute(&result).is_err());
        assert_eq!(o.status, MarketOrderStatus::Rejected);
    }

    #[test]
    fn test_estimate_slippage() {
        let o = MarketOrder::new(1, MarketSide::Buy, 80.0);
        let est = o.estimate_slippage(&sample_ladder(), 100.0).unwrap();
        assert!(est.can_fill);
        assert!(est.slippage_bps > 0.0);
    }

    #[test]
    fn test_estimate_cant_fill() {
        let o = MarketOrder::new(1, MarketSide::Buy, 500.0);
        let est = o.estimate_slippage(&sample_ladder(), 100.0).unwrap();
        assert!(!est.can_fill);
    }

    #[test]
    fn test_avg_fill_price() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 80.0);
        let result = o.simulate_fill(&sample_ladder(), 100.0).unwrap();
        o.execute(&result).unwrap();
        assert!(o.avg_fill_price().is_some());
    }

    #[test]
    fn test_price_impact() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 80.0);
        let result = o.simulate_fill(&sample_ladder(), 100.0).unwrap();
        o.execute(&result).unwrap();
        let impact = o.price_impact().unwrap();
        assert!(impact > 0.0);
    }

    #[test]
    fn test_fill_ratio() {
        let mut o = MarketOrder::new(1, MarketSide::Buy, 200.0);
        let result = o.simulate_fill(&sample_ladder(), 100.0).unwrap();
        o.execute(&result).unwrap();
        assert!((o.fill_ratio() - 0.9).abs() < 1e-6); // 180/200
    }

    #[test]
    fn test_builder_chain() {
        let o = MarketOrder::new(1, MarketSide::Sell, 100.0)
            .with_created_ns(5000)
            .with_client_order_id("mkt-42")
            .with_max_slippage_bps(50.0);
        assert_eq!(o.created_ns, 5000);
        assert_eq!(o.client_order_id.as_deref(), Some("mkt-42"));
        assert_eq!(o.max_slippage_bps, Some(50.0));
    }

    #[test]
    fn test_display() {
        let o = MarketOrder::new(7, MarketSide::Buy, 100.0);
        let s = format!("{o}");
        assert!(s.contains("MKT-BUY"));
        assert!(s.contains("7"));
    }

    #[test]
    fn test_fill_result_display() {
        let result = FillResult {
            fills: vec![],
            total_filled: 50.0,
            unfilled: 0.0,
            avg_price: 100.0,
            total_notional: 5000.0,
            slippage_bps: 5.0,
            levels_consumed: 2,
            vwap: 100.0,
        };
        let s = format!("{result}");
        assert!(s.contains("5.0bps"));
    }

    #[test]
    fn test_side_display() {
        assert_eq!(format!("{}", MarketSide::Buy), "MKT-BUY");
        assert_eq!(format!("{}", MarketSide::Sell), "MKT-SELL");
    }
}
