//! Order Matching Engine — price-time FIFO matching, pro-rata matching,
//! trade generation, and match statistics tracking.
//!
//! Pure-Rust order matching engine supporting both price-time-priority
//! (FIFO) and pro-rata allocation modes with trade event emission and
//! cumulative statistics.

use std::collections::BTreeMap;
use std::fmt;

// ── Errors ──────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub enum MatchError {
    InvalidOrder(String),
    EmptyBook,
    NoMatch(String),
    InternalError(String),
}

impl fmt::Display for MatchError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidOrder(s) => write!(f, "invalid order: {s}"),
            Self::EmptyBook => write!(f, "empty book"),
            Self::NoMatch(s) => write!(f, "no match: {s}"),
            Self::InternalError(s) => write!(f, "internal error: {s}"),
        }
    }
}

impl std::error::Error for MatchError {}

// ── MatchMode ───────────────────────────────────────────────────

/// The matching algorithm to use.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MatchMode {
    /// Price-time priority (FIFO): earliest order at best price fills first.
    PriceTimeFifo,
    /// Pro-rata: orders at the same price share fills proportionally.
    ProRata,
}

impl fmt::Display for MatchMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::PriceTimeFifo => write!(f, "FIFO"),
            Self::ProRata => write!(f, "PRO-RATA"),
        }
    }
}

// ── MatchSide ───────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MatchSide {
    Buy,
    Sell,
}

impl fmt::Display for MatchSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Buy => write!(f, "BUY"),
            Self::Sell => write!(f, "SELL"),
        }
    }
}

// ── RestingOrder ────────────────────────────────────────────────

/// An order resting on the book, available for matching.
#[derive(Debug, Clone, PartialEq)]
pub struct RestingOrder {
    pub order_id: u64,
    pub side: MatchSide,
    pub price: f64,
    pub remaining: f64,
    pub timestamp_ns: u64,
}

impl RestingOrder {
    pub fn new(order_id: u64, side: MatchSide, price: f64, remaining: f64, ts: u64) -> Self {
        Self { order_id, side, price, remaining, timestamp_ns: ts }
    }

    pub fn is_filled(&self) -> bool { self.remaining <= 1e-12 }
}

impl fmt::Display for RestingOrder {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Resting(id={}, {} {:.4}@{:.2})", self.order_id, self.side, self.remaining, self.price)
    }
}

// ── IncomingOrder ───────────────────────────────────────────────

/// An incoming aggressive order to match against the book.
#[derive(Debug, Clone, PartialEq)]
pub struct IncomingOrder {
    pub order_id: u64,
    pub side: MatchSide,
    pub price: Option<f64>,
    pub quantity: f64,
    pub remaining: f64,
    pub timestamp_ns: u64,
}

impl IncomingOrder {
    /// Limit aggressor.
    pub fn limit(order_id: u64, side: MatchSide, price: f64, qty: f64, ts: u64) -> Self {
        Self { order_id, side, price: Some(price), quantity: qty, remaining: qty, timestamp_ns: ts }
    }

    /// Market aggressor (no price limit).
    pub fn market(order_id: u64, side: MatchSide, qty: f64, ts: u64) -> Self {
        Self { order_id, side, price: None, quantity: qty, remaining: qty, timestamp_ns: ts }
    }

    pub fn is_filled(&self) -> bool { self.remaining <= 1e-12 }

    /// Whether this order can match at the given price.
    pub fn can_match_at(&self, resting_price: f64) -> bool {
        match self.price {
            None => true, // market order matches any price
            Some(limit) => match self.side {
                MatchSide::Buy => limit >= resting_price,
                MatchSide::Sell => limit <= resting_price,
            },
        }
    }
}

impl fmt::Display for IncomingOrder {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let px = self.price.map_or("MKT".into(), |p| format!("{p:.2}"));
        write!(f, "Incoming(id={}, {} {:.4}@{px})", self.order_id, self.side, self.remaining)
    }
}

// ── Trade ───────────────────────────────────────────────────────

/// A trade generated by matching two orders.
#[derive(Debug, Clone, PartialEq)]
pub struct Trade {
    pub trade_id: u64,
    pub aggressor_id: u64,
    pub resting_id: u64,
    pub price: f64,
    pub quantity: f64,
    pub timestamp_ns: u64,
    pub aggressor_side: MatchSide,
}

impl Trade {
    pub fn notional(&self) -> f64 { self.price * self.quantity }
}

impl fmt::Display for Trade {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Trade(id={}, {:.4}@{:.2}, agg={}, rest={})",
            self.trade_id, self.quantity, self.price, self.aggressor_id, self.resting_id)
    }
}

// ── MatchResult ─────────────────────────────────────────────────

/// The outcome of a match attempt.
#[derive(Debug, Clone)]
pub struct MatchResult {
    pub trades: Vec<Trade>,
    pub total_filled: f64,
    pub unfilled: f64,
    pub levels_consumed: usize,
    pub avg_price: f64,
}

impl MatchResult {
    pub fn is_complete(&self) -> bool { self.unfilled < 1e-12 }
}

impl fmt::Display for MatchResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MatchResult(trades={}, filled={:.4}, unfilled={:.4}, avg={:.4})",
            self.trades.len(), self.total_filled, self.unfilled, self.avg_price)
    }
}

// ── MatchStats ──────────────────────────────────────────────────

/// Cumulative matching engine statistics.
#[derive(Debug, Clone)]
pub struct MatchStats {
    pub total_trades: u64,
    pub total_volume: f64,
    pub total_notional: f64,
    pub orders_processed: u64,
    pub full_fills: u64,
    pub partial_fills: u64,
}

impl MatchStats {
    fn new() -> Self {
        Self {
            total_trades: 0, total_volume: 0.0, total_notional: 0.0,
            orders_processed: 0, full_fills: 0, partial_fills: 0,
        }
    }

    /// Average trade size.
    pub fn avg_trade_size(&self) -> f64 {
        if self.total_trades == 0 { 0.0 } else { self.total_volume / self.total_trades as f64 }
    }

    /// Fill ratio (full fills / orders processed).
    pub fn fill_rate(&self) -> f64 {
        if self.orders_processed == 0 { 0.0 }
        else { self.full_fills as f64 / self.orders_processed as f64 }
    }
}

impl fmt::Display for MatchStats {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Stats(trades={}, vol={:.2}, notional={:.2}, fill_rate={:.1}%)",
            self.total_trades, self.total_volume, self.total_notional, self.fill_rate() * 100.0)
    }
}

// ── OrderMatchEngine ────────────────────────────────────────────

/// An order matching engine with configurable match mode.
#[derive(Debug, Clone)]
pub struct OrderMatchEngine {
    mode: MatchMode,
    bids: BTreeMap<i64, Vec<RestingOrder>>,
    asks: BTreeMap<i64, Vec<RestingOrder>>,
    tick_size: f64,
    next_trade_id: u64,
    stats: MatchStats,
}

fn to_ticks(price: f64, tick_size: f64) -> i64 {
    (price / tick_size).round() as i64
}

fn from_ticks(ticks: i64, tick_size: f64) -> f64 {
    ticks as f64 * tick_size
}

impl OrderMatchEngine {
    pub fn new(mode: MatchMode) -> Self {
        Self {
            mode,
            bids: BTreeMap::new(),
            asks: BTreeMap::new(),
            tick_size: 0.01,
            next_trade_id: 1,
            stats: MatchStats::new(),
        }
    }

    pub fn with_tick_size(mut self, ts: f64) -> Self {
        self.tick_size = ts;
        self
    }

    /// Add a resting order to the book.
    pub fn add_resting(&mut self, order: RestingOrder) {
        let ticks = to_ticks(order.price, self.tick_size);
        let book = match order.side {
            MatchSide::Buy => &mut self.bids,
            MatchSide::Sell => &mut self.asks,
        };
        book.entry(ticks).or_default().push(order);
    }

    /// Match an incoming order against the book.
    pub fn match_order(&mut self, incoming: &mut IncomingOrder) -> Result<MatchResult, MatchError> {
        if incoming.remaining <= 0.0 {
            return Err(MatchError::InvalidOrder("zero quantity".into()));
        }
        let trades = match self.mode {
            MatchMode::PriceTimeFifo => self.match_fifo(incoming)?,
            MatchMode::ProRata => self.match_pro_rata(incoming)?,
        };
        let total_filled: f64 = trades.iter().map(|t| t.quantity).sum();
        let total_notional: f64 = trades.iter().map(|t| t.notional()).sum();
        let avg_price = if total_filled > 1e-12 { total_notional / total_filled } else { 0.0 };
        let levels = trades.iter().map(|t| to_ticks(t.price, self.tick_size))
            .collect::<std::collections::HashSet<_>>().len();

        // update stats
        self.stats.total_trades += trades.len() as u64;
        self.stats.total_volume += total_filled;
        self.stats.total_notional += total_notional;
        self.stats.orders_processed += 1;
        if incoming.is_filled() { self.stats.full_fills += 1; }
        else if total_filled > 1e-12 { self.stats.partial_fills += 1; }

        Ok(MatchResult {
            trades,
            total_filled,
            unfilled: incoming.remaining,
            levels_consumed: levels,
            avg_price,
        })
    }

    fn match_fifo(&mut self, incoming: &mut IncomingOrder) -> Result<Vec<Trade>, MatchError> {
        let mut trades = Vec::new();
        let opposite = match incoming.side {
            MatchSide::Buy => &mut self.asks,
            MatchSide::Sell => &mut self.bids,
        };

        let price_keys: Vec<i64> = match incoming.side {
            MatchSide::Buy => opposite.keys().cloned().collect(),
            MatchSide::Sell => opposite.keys().rev().cloned().collect(),
        };

        for ticks in price_keys {
            if incoming.is_filled() { break; }
            let resting_price = from_ticks(ticks, self.tick_size);
            if !incoming.can_match_at(resting_price) { break; }

            if let Some(orders) = opposite.get_mut(&ticks) {
                let mut i = 0;
                while i < orders.len() && !incoming.is_filled() {
                    let fill_qty = incoming.remaining.min(orders[i].remaining);
                    if fill_qty > 1e-12 {
                        trades.push(Trade {
                            trade_id: self.next_trade_id,
                            aggressor_id: incoming.order_id,
                            resting_id: orders[i].order_id,
                            price: resting_price,
                            quantity: fill_qty,
                            timestamp_ns: incoming.timestamp_ns,
                            aggressor_side: incoming.side,
                        });
                        self.next_trade_id += 1;
                        incoming.remaining -= fill_qty;
                        orders[i].remaining -= fill_qty;
                    }
                    i += 1;
                }
                orders.retain(|o| !o.is_filled());
            }
        }

        // Clean up empty price levels.
        let opposite = match incoming.side {
            MatchSide::Buy => &mut self.asks,
            MatchSide::Sell => &mut self.bids,
        };
        opposite.retain(|_, v| !v.is_empty());

        Ok(trades)
    }

    fn match_pro_rata(&mut self, incoming: &mut IncomingOrder) -> Result<Vec<Trade>, MatchError> {
        let mut trades = Vec::new();
        let opposite = match incoming.side {
            MatchSide::Buy => &mut self.asks,
            MatchSide::Sell => &mut self.bids,
        };

        let price_keys: Vec<i64> = match incoming.side {
            MatchSide::Buy => opposite.keys().cloned().collect(),
            MatchSide::Sell => opposite.keys().rev().cloned().collect(),
        };

        for ticks in price_keys {
            if incoming.is_filled() { break; }
            let resting_price = from_ticks(ticks, self.tick_size);
            if !incoming.can_match_at(resting_price) { break; }

            if let Some(orders) = opposite.get_mut(&ticks) {
                let total_at_level: f64 = orders.iter().map(|o| o.remaining).sum();
                let available = incoming.remaining.min(total_at_level);

                if available > 1e-12 && total_at_level > 1e-12 {
                    for order in orders.iter_mut() {
                        let share = (order.remaining / total_at_level) * available;
                        let fill_qty = share.min(order.remaining);
                        if fill_qty > 1e-12 {
                            trades.push(Trade {
                                trade_id: self.next_trade_id,
                                aggressor_id: incoming.order_id,
                                resting_id: order.order_id,
                                price: resting_price,
                                quantity: fill_qty,
                                timestamp_ns: incoming.timestamp_ns,
                                aggressor_side: incoming.side,
                            });
                            self.next_trade_id += 1;
                            incoming.remaining -= fill_qty;
                            order.remaining -= fill_qty;
                        }
                    }
                }
                orders.retain(|o| !o.is_filled());
            }
        }

        let opposite = match incoming.side {
            MatchSide::Buy => &mut self.asks,
            MatchSide::Sell => &mut self.bids,
        };
        opposite.retain(|_, v| !v.is_empty());

        Ok(trades)
    }

    pub fn stats(&self) -> &MatchStats { &self.stats }

    pub fn mode(&self) -> MatchMode { self.mode }

    /// Count of resting orders on each side.
    pub fn resting_count(&self) -> (usize, usize) {
        let bids: usize = self.bids.values().map(|v| v.len()).sum();
        let asks: usize = self.asks.values().map(|v| v.len()).sum();
        (bids, asks)
    }
}

impl fmt::Display for OrderMatchEngine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let (b, a) = self.resting_count();
        write!(f, "MatchEngine(mode={}, bids={b}, asks={a}, trades={})",
            self.mode, self.stats.total_trades)
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn engine_with_book() -> OrderMatchEngine {
        let mut e = OrderMatchEngine::new(MatchMode::PriceTimeFifo);
        e.add_resting(RestingOrder::new(10, MatchSide::Sell, 100.0, 50.0, 1000));
        e.add_resting(RestingOrder::new(11, MatchSide::Sell, 100.0, 30.0, 2000));
        e.add_resting(RestingOrder::new(12, MatchSide::Sell, 101.0, 100.0, 3000));
        e.add_resting(RestingOrder::new(20, MatchSide::Buy, 99.0, 40.0, 1000));
        e
    }

    #[test]
    fn test_fifo_single_fill() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::limit(1, MatchSide::Buy, 100.0, 30.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert_eq!(result.trades.len(), 1);
        assert!((result.total_filled - 30.0).abs() < 1e-6);
        assert!(inc.is_filled());
    }

    #[test]
    fn test_fifo_multi_fill() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::limit(1, MatchSide::Buy, 100.0, 70.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert_eq!(result.trades.len(), 2); // 50 from id=10, 20 from id=11
        assert!((result.total_filled - 70.0).abs() < 1e-6);
    }

    #[test]
    fn test_fifo_cross_levels() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::limit(1, MatchSide::Buy, 101.0, 100.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert!(result.trades.len() >= 3);
        assert!((result.total_filled - 100.0).abs() < 1e-6);
    }

    #[test]
    fn test_fifo_no_match() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::limit(1, MatchSide::Buy, 98.0, 50.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert_eq!(result.trades.len(), 0);
        assert!((result.unfilled - 50.0).abs() < 1e-6);
    }

    #[test]
    fn test_market_order_fill() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::market(1, MatchSide::Buy, 50.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert!((result.total_filled - 50.0).abs() < 1e-6);
        assert!(inc.is_filled());
    }

    #[test]
    fn test_sell_aggressor() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::limit(1, MatchSide::Sell, 99.0, 20.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert_eq!(result.trades.len(), 1);
        assert!((result.total_filled - 20.0).abs() < 1e-6);
    }

    #[test]
    fn test_pro_rata() {
        let mut e = OrderMatchEngine::new(MatchMode::ProRata);
        e.add_resting(RestingOrder::new(10, MatchSide::Sell, 100.0, 60.0, 1000));
        e.add_resting(RestingOrder::new(11, MatchSide::Sell, 100.0, 40.0, 2000));
        let mut inc = IncomingOrder::limit(1, MatchSide::Buy, 100.0, 50.0, 5000);
        let result = e.match_order(&mut inc).unwrap();
        assert_eq!(result.trades.len(), 2);
        // 60% to id=10 (30), 40% to id=11 (20)
        let t10 = result.trades.iter().find(|t| t.resting_id == 10).unwrap();
        let t11 = result.trades.iter().find(|t| t.resting_id == 11).unwrap();
        assert!((t10.quantity - 30.0).abs() < 1e-6);
        assert!((t11.quantity - 20.0).abs() < 1e-6);
    }

    #[test]
    fn test_stats_tracking() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::market(1, MatchSide::Buy, 50.0, 5000);
        e.match_order(&mut inc).unwrap();
        assert!(e.stats().total_trades > 0);
        assert!(e.stats().total_volume > 0.0);
        assert_eq!(e.stats().orders_processed, 1);
    }

    #[test]
    fn test_resting_count() {
        let e = engine_with_book();
        let (b, a) = e.resting_count();
        assert_eq!(b, 1);
        assert_eq!(a, 3);
    }

    #[test]
    fn test_invalid_zero_qty() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::market(1, MatchSide::Buy, 0.0, 5000);
        assert!(e.match_order(&mut inc).is_err());
    }

    #[test]
    fn test_trade_display() {
        let t = Trade {
            trade_id: 1, aggressor_id: 2, resting_id: 3,
            price: 100.0, quantity: 50.0, timestamp_ns: 1000,
            aggressor_side: MatchSide::Buy,
        };
        let s = format!("{t}");
        assert!(s.contains("50.0000"));
        assert!(s.contains("100.00"));
    }

    #[test]
    fn test_match_result_display() {
        let r = MatchResult {
            trades: vec![], total_filled: 50.0, unfilled: 10.0,
            levels_consumed: 2, avg_price: 100.0,
        };
        let s = format!("{r}");
        assert!(s.contains("50.0000"));
    }

    #[test]
    fn test_engine_display() {
        let e = engine_with_book();
        let s = format!("{e}");
        assert!(s.contains("FIFO"));
    }

    #[test]
    fn test_stats_fill_rate() {
        let mut e = engine_with_book();
        let mut inc = IncomingOrder::market(1, MatchSide::Buy, 50.0, 5000);
        e.match_order(&mut inc).unwrap();
        assert!(e.stats().fill_rate() > 0.0);
    }

    #[test]
    fn test_incoming_display() {
        let inc = IncomingOrder::limit(7, MatchSide::Buy, 99.50, 100.0, 1000);
        let s = format!("{inc}");
        assert!(s.contains("99.50"));
    }

    #[test]
    fn test_match_result_complete() {
        let r = MatchResult {
            trades: vec![], total_filled: 50.0, unfilled: 0.0,
            levels_consumed: 1, avg_price: 100.0,
        };
        assert!(r.is_complete());
    }

    #[test]
    fn test_resting_order_display() {
        let o = RestingOrder::new(5, MatchSide::Sell, 101.0, 200.0, 1000);
        let s = format!("{o}");
        assert!(s.contains("SELL"));
        assert!(s.contains("101.00"));
    }
}
