//! Rebalancing engine — threshold-based triggers, calendar rebalance,
//! tax-aware rebalance (harvest losses), transaction cost minimisation,
//! and drift monitoring.
//!
//! Pure Rust, std-only. All floating-point values are `f64`.

use std::fmt;

// ── DriftMetrics ────────────────────────────────────────────────

/// Per-asset and portfolio-level drift measurements.
#[derive(Debug, Clone)]
pub struct DriftMetrics {
    pub asset_drifts: Vec<f64>,
    pub max_drift: f64,
    pub mean_drift: f64,
    pub sum_absolute_drift: f64,
}

impl DriftMetrics {
    /// Compute drift between current and target weights.
    pub fn compute(current_weights: &[f64], target_weights: &[f64]) -> Self {
        let drifts: Vec<f64> = current_weights
            .iter()
            .zip(target_weights.iter())
            .map(|(c, t)| c - t)
            .collect();
        let abs_drifts: Vec<f64> = drifts.iter().map(|d| d.abs()).collect();
        let max_drift = abs_drifts.iter().cloned().fold(0.0_f64, f64::max);
        let sum_abs = abs_drifts.iter().sum::<f64>();
        let mean_drift = if drifts.is_empty() {
            0.0
        } else {
            sum_abs / drifts.len() as f64
        };
        Self {
            asset_drifts: drifts,
            max_drift,
            mean_drift,
            sum_absolute_drift: sum_abs,
        }
    }

    /// Which assets exceed a given threshold.
    pub fn assets_exceeding(&self, threshold: f64) -> Vec<usize> {
        self.asset_drifts
            .iter()
            .enumerate()
            .filter(|(_, d)| d.abs() > threshold)
            .map(|(i, _)| i)
            .collect()
    }
}

impl fmt::Display for DriftMetrics {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Drift(max={:.2}%, mean={:.2}%, sum_abs={:.2}%)",
            self.max_drift * 100.0,
            self.mean_drift * 100.0,
            self.sum_absolute_drift * 100.0
        )
    }
}

// ── RebalanceTrigger ────────────────────────────────────────────

/// Policy for when to trigger a rebalance.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum RebalanceTrigger {
    /// Rebalance if any asset drifts beyond `threshold` (absolute).
    Threshold(f64),
    /// Rebalance on a fixed calendar interval (days).
    Calendar(u32),
    /// Rebalance if total absolute drift exceeds `threshold`.
    TotalDrift(f64),
    /// Combine threshold and calendar: whichever fires first.
    ThresholdOrCalendar(f64, u32),
}

impl RebalanceTrigger {
    /// Check if rebalance should fire given drift and days since last rebalance.
    pub fn should_rebalance(&self, drift: &DriftMetrics, days_since: u32) -> bool {
        match *self {
            Self::Threshold(t) => drift.max_drift > t,
            Self::Calendar(interval) => days_since >= interval,
            Self::TotalDrift(t) => drift.sum_absolute_drift > t,
            Self::ThresholdOrCalendar(t, interval) => {
                drift.max_drift > t || days_since >= interval
            }
        }
    }
}

impl fmt::Display for RebalanceTrigger {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Threshold(t) => write!(f, "Threshold({:.1}%)", t * 100.0),
            Self::Calendar(d) => write!(f, "Calendar({d}d)"),
            Self::TotalDrift(t) => write!(f, "TotalDrift({:.1}%)", t * 100.0),
            Self::ThresholdOrCalendar(t, d) => {
                write!(f, "ThresholdOrCalendar({:.1}%, {d}d)", t * 100.0)
            }
        }
    }
}

// ── TradeOrder ──────────────────────────────────────────────────

/// A proposed trade generated by the rebalance engine.
#[derive(Debug, Clone)]
pub struct TradeOrder {
    pub asset_index: usize,
    pub amount: f64,
    pub is_buy: bool,
    pub estimated_cost: f64,
}

impl TradeOrder {
    pub fn new(asset_index: usize, amount: f64, cost_bps: f64) -> Self {
        let is_buy = amount >= 0.0;
        let estimated_cost = amount.abs() * cost_bps / 10_000.0;
        Self {
            asset_index,
            amount,
            is_buy,
            estimated_cost,
        }
    }

    pub fn net_amount(&self) -> f64 {
        if self.is_buy {
            self.amount - self.estimated_cost
        } else {
            self.amount + self.estimated_cost
        }
    }
}

impl fmt::Display for TradeOrder {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let side = if self.is_buy { "BUY" } else { "SELL" };
        write!(
            f,
            "Trade({side} asset[{}] ${:.2}, cost=${:.2})",
            self.asset_index,
            self.amount.abs(),
            self.estimated_cost
        )
    }
}

// ── RebalanceConfig ─────────────────────────────────────────────

/// Configuration for the rebalancing engine.
#[derive(Debug, Clone)]
pub struct RebalanceConfig {
    pub trigger: RebalanceTrigger,
    pub cost_bps: f64,
    pub min_trade_size: f64,
    pub tax_aware: bool,
    pub loss_harvest_threshold: f64,
}

impl RebalanceConfig {
    pub fn new(trigger: RebalanceTrigger) -> Self {
        Self {
            trigger,
            cost_bps: 10.0,
            min_trade_size: 100.0,
            tax_aware: false,
            loss_harvest_threshold: 0.0,
        }
    }

    pub fn with_cost_bps(mut self, bps: f64) -> Self {
        self.cost_bps = bps;
        self
    }

    pub fn with_min_trade_size(mut self, size: f64) -> Self {
        self.min_trade_size = size;
        self
    }

    pub fn with_tax_aware(mut self, flag: bool) -> Self {
        self.tax_aware = flag;
        self
    }

    pub fn with_loss_harvest_threshold(mut self, thresh: f64) -> Self {
        self.loss_harvest_threshold = thresh;
        self
    }
}

impl fmt::Display for RebalanceConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "RebalanceConfig(trigger={}, cost={:.1}bps, tax_aware={})",
            self.trigger, self.cost_bps, self.tax_aware
        )
    }
}

// ── RebalanceEngine ─────────────────────────────────────────────

/// Generates trade orders to rebalance a portfolio.
#[derive(Debug)]
pub struct RebalanceEngine {
    pub config: RebalanceConfig,
    pub rebalance_count: u64,
    pub total_cost: f64,
}

impl RebalanceEngine {
    pub fn new(config: RebalanceConfig) -> Self {
        Self {
            config,
            rebalance_count: 0,
            total_cost: 0.0,
        }
    }

    /// Generate trade orders to move from current to target weights.
    pub fn generate_trades(
        &mut self,
        current_values: &[f64],
        target_weights: &[f64],
    ) -> Vec<TradeOrder> {
        let total_value: f64 = current_values.iter().sum();
        if total_value < 1e-10 {
            return Vec::new();
        }

        let mut trades = Vec::new();
        for (i, (&current, &target)) in current_values
            .iter()
            .zip(target_weights.iter())
            .enumerate()
        {
            let target_val = target * total_value;
            let diff = target_val - current;
            if diff.abs() >= self.config.min_trade_size {
                trades.push(TradeOrder::new(i, diff, self.config.cost_bps));
            }
        }

        self.rebalance_count += 1;
        let cost: f64 = trades.iter().map(|t| t.estimated_cost).sum();
        self.total_cost += cost;
        trades
    }

    /// Check drift and conditionally rebalance.
    pub fn maybe_rebalance(
        &mut self,
        current_values: &[f64],
        target_weights: &[f64],
        days_since_last: u32,
    ) -> Option<Vec<TradeOrder>> {
        let total: f64 = current_values.iter().sum();
        if total < 1e-10 {
            return None;
        }
        let current_weights: Vec<f64> = current_values.iter().map(|v| v / total).collect();
        let drift = DriftMetrics::compute(&current_weights, target_weights);

        if self.config.trigger.should_rebalance(&drift, days_since_last) {
            Some(self.generate_trades(current_values, target_weights))
        } else {
            None
        }
    }
}

impl fmt::Display for RebalanceEngine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "RebalanceEngine(count={}, total_cost=${:.2})",
            self.rebalance_count, self.total_cost
        )
    }
}

// ── Tax-Aware Rebalance ─────────────────────────────────────────

/// A tax lot with cost basis and gain/loss tracking.
#[derive(Debug, Clone)]
pub struct TaxLot {
    pub asset_index: usize,
    pub quantity: f64,
    pub cost_basis: f64,
    pub current_value: f64,
    pub holding_days: u32,
}

impl TaxLot {
    pub fn new(
        asset_index: usize,
        quantity: f64,
        cost_basis: f64,
        current_value: f64,
        holding_days: u32,
    ) -> Self {
        Self {
            asset_index,
            quantity,
            cost_basis,
            current_value,
            holding_days,
        }
    }

    pub fn unrealized_gain(&self) -> f64 {
        self.current_value - self.cost_basis
    }

    pub fn is_long_term(&self) -> bool {
        self.holding_days > 365
    }

    pub fn is_loss(&self) -> bool {
        self.unrealized_gain() < 0.0
    }
}

impl fmt::Display for TaxLot {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let term = if self.is_long_term() { "LT" } else { "ST" };
        write!(
            f,
            "TaxLot(asset[{}], gain=${:.2}, {term})",
            self.asset_index,
            self.unrealized_gain()
        )
    }
}

/// Identify tax-loss harvesting opportunities.
pub fn harvest_losses(lots: &[TaxLot], min_loss: f64) -> Vec<usize> {
    lots.iter()
        .enumerate()
        .filter(|(_, lot)| lot.is_loss() && lot.unrealized_gain().abs() >= min_loss)
        .map(|(i, _)| i)
        .collect()
}

// ── Transaction Cost Minimiser ──────────────────────────────────

/// Adjust trade amounts to minimise transaction costs while staying within
/// a tolerance band around target weights.
pub fn minimise_transaction_costs(
    trades: &mut [TradeOrder],
    tolerance: f64,
    total_portfolio_value: f64,
) -> f64 {
    let mut saved = 0.0;
    for trade in trades.iter_mut() {
        let trade_pct = trade.amount.abs() / total_portfolio_value;
        if trade_pct < tolerance {
            saved += trade.estimated_cost;
            trade.amount = 0.0;
            trade.estimated_cost = 0.0;
        }
    }
    saved
}

// ── Drift Monitor ───────────────────────────────────────────────

/// Tracks portfolio drift over time.
#[derive(Debug, Clone)]
pub struct DriftMonitor {
    pub history: Vec<DriftMetrics>,
    pub max_observations: usize,
}

impl DriftMonitor {
    pub fn new(max_observations: usize) -> Self {
        Self {
            history: Vec::new(),
            max_observations,
        }
    }

    pub fn record(&mut self, current: &[f64], target: &[f64]) {
        let dm = DriftMetrics::compute(current, target);
        if self.history.len() >= self.max_observations {
            self.history.remove(0);
        }
        self.history.push(dm);
    }

    pub fn average_max_drift(&self) -> f64 {
        if self.history.is_empty() {
            return 0.0;
        }
        let s: f64 = self.history.iter().map(|d| d.max_drift).sum();
        s / self.history.len() as f64
    }

    pub fn peak_drift(&self) -> f64 {
        self.history
            .iter()
            .map(|d| d.max_drift)
            .fold(0.0_f64, f64::max)
    }
}

impl fmt::Display for DriftMonitor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "DriftMonitor(obs={}, avg_max={:.2}%)",
            self.history.len(),
            self.average_max_drift() * 100.0
        )
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_drift_compute() {
        let current = vec![0.65, 0.25, 0.10];
        let target = vec![0.60, 0.30, 0.10];
        let dm = DriftMetrics::compute(&current, &target);
        assert!((dm.asset_drifts[0] - 0.05).abs() < 1e-10);
        assert!((dm.asset_drifts[1] - (-0.05)).abs() < 1e-10);
        assert!((dm.max_drift - 0.05).abs() < 1e-10);
    }

    #[test]
    fn test_drift_display() {
        let dm = DriftMetrics::compute(&[0.55, 0.45], &[0.50, 0.50]);
        let s = format!("{dm}");
        assert!(s.contains("Drift("));
    }

    #[test]
    fn test_drift_assets_exceeding() {
        let dm = DriftMetrics::compute(&[0.70, 0.20, 0.10], &[0.60, 0.30, 0.10]);
        let exceeded = dm.assets_exceeding(0.05);
        assert_eq!(exceeded.len(), 2); // equity and bonds exceed 5%
    }

    #[test]
    fn test_threshold_trigger() {
        let trigger = RebalanceTrigger::Threshold(0.05);
        let drift = DriftMetrics::compute(&[0.66, 0.24, 0.10], &[0.60, 0.30, 0.10]);
        assert!(trigger.should_rebalance(&drift, 0));
    }

    #[test]
    fn test_calendar_trigger() {
        let trigger = RebalanceTrigger::Calendar(90);
        let drift = DriftMetrics::compute(&[0.60, 0.30, 0.10], &[0.60, 0.30, 0.10]);
        assert!(!trigger.should_rebalance(&drift, 89));
        assert!(trigger.should_rebalance(&drift, 90));
    }

    #[test]
    fn test_trigger_display() {
        let t = RebalanceTrigger::Threshold(0.05);
        assert!(format!("{t}").contains("5.0%"));
    }

    #[test]
    fn test_trade_order_buy() {
        let t = TradeOrder::new(0, 1000.0, 10.0);
        assert!(t.is_buy);
        assert!((t.estimated_cost - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_trade_order_sell() {
        let t = TradeOrder::new(1, -500.0, 10.0);
        assert!(!t.is_buy);
        assert!((t.estimated_cost - 0.50).abs() < 1e-10);
    }

    #[test]
    fn test_trade_order_display() {
        let t = TradeOrder::new(0, 1000.0, 10.0);
        let s = format!("{t}");
        assert!(s.contains("BUY"));
    }

    #[test]
    fn test_rebalance_config_builder() {
        let c = RebalanceConfig::new(RebalanceTrigger::Threshold(0.05))
            .with_cost_bps(15.0)
            .with_min_trade_size(50.0)
            .with_tax_aware(true)
            .with_loss_harvest_threshold(500.0);
        assert!((c.cost_bps - 15.0).abs() < 1e-10);
        assert!(c.tax_aware);
    }

    #[test]
    fn test_generate_trades() {
        let config = RebalanceConfig::new(RebalanceTrigger::Threshold(0.05));
        let mut engine = RebalanceEngine::new(config);
        let current = vec![7000.0, 2000.0, 1000.0];
        let target = vec![0.60, 0.30, 0.10];
        let trades = engine.generate_trades(&current, &target);
        assert!(!trades.is_empty());
        assert_eq!(engine.rebalance_count, 1);
    }

    #[test]
    fn test_maybe_rebalance_triggers() {
        let config = RebalanceConfig::new(RebalanceTrigger::Threshold(0.03));
        let mut engine = RebalanceEngine::new(config);
        let current = vec![7000.0, 2000.0, 1000.0];
        let target = vec![0.60, 0.30, 0.10];
        let result = engine.maybe_rebalance(&current, &target, 0);
        assert!(result.is_some());
    }

    #[test]
    fn test_maybe_rebalance_no_trigger() {
        let config = RebalanceConfig::new(RebalanceTrigger::Threshold(0.20));
        let mut engine = RebalanceEngine::new(config);
        let current = vec![6000.0, 3000.0, 1000.0];
        let target = vec![0.60, 0.30, 0.10];
        let result = engine.maybe_rebalance(&current, &target, 0);
        assert!(result.is_none());
    }

    #[test]
    fn test_tax_lot_gain() {
        let lot = TaxLot::new(0, 100.0, 10000.0, 12000.0, 400);
        assert!((lot.unrealized_gain() - 2000.0).abs() < 1e-10);
        assert!(lot.is_long_term());
        assert!(!lot.is_loss());
    }

    #[test]
    fn test_tax_lot_loss() {
        let lot = TaxLot::new(0, 50.0, 5000.0, 4000.0, 100);
        assert!(lot.is_loss());
        assert!(!lot.is_long_term());
    }

    #[test]
    fn test_harvest_losses() {
        let lots = vec![
            TaxLot::new(0, 100.0, 10000.0, 9000.0, 200),
            TaxLot::new(1, 50.0, 5000.0, 5500.0, 100),
            TaxLot::new(2, 75.0, 7500.0, 6000.0, 300),
        ];
        let harvested = harvest_losses(&lots, 500.0);
        assert_eq!(harvested.len(), 2); // lots 0 and 2 have losses > $500
    }

    #[test]
    fn test_minimise_costs() {
        let mut trades = vec![
            TradeOrder::new(0, 50.0, 10.0),
            TradeOrder::new(1, -2000.0, 10.0),
        ];
        let saved = minimise_transaction_costs(&mut trades, 0.01, 10000.0);
        assert!(saved > 0.0); // the $50 trade is < 1% so should be eliminated
        assert!((trades[0].amount).abs() < 1e-10);
    }

    #[test]
    fn test_drift_monitor() {
        let mut monitor = DriftMonitor::new(10);
        monitor.record(&[0.65, 0.25, 0.10], &[0.60, 0.30, 0.10]);
        monitor.record(&[0.62, 0.28, 0.10], &[0.60, 0.30, 0.10]);
        assert_eq!(monitor.history.len(), 2);
        assert!(monitor.average_max_drift() > 0.0);
        assert!(monitor.peak_drift() >= monitor.average_max_drift());
    }

    #[test]
    fn test_drift_monitor_display() {
        let monitor = DriftMonitor::new(10);
        let s = format!("{monitor}");
        assert!(s.contains("DriftMonitor"));
    }

    #[test]
    fn test_engine_display() {
        let config = RebalanceConfig::new(RebalanceTrigger::Calendar(90));
        let engine = RebalanceEngine::new(config);
        let s = format!("{engine}");
        assert!(s.contains("RebalanceEngine"));
    }
}
