//! Accessibility Infrastructure — legal mandate (ADA, EAA) compliance.
//!
//! Content platforms must provide:
//! - Caption/subtitle storage with time alignment
//! - Content complexity scoring (reading level, visual intensity)
//! - Photosensitive epilepsy warnings (flash/flicker detection)

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::{RecordId, Value};

/// A timed caption/subtitle entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Caption {
    /// Start time in milliseconds
    pub start_ms: u64,
    /// End time in milliseconds
    pub end_ms: u64,
    /// Caption text
    pub text: String,
    /// Speaker identifier (for diarization)
    pub speaker: Option<String>,
    /// Language code (ISO 639-1)
    pub language: String,
}

/// A complete caption track for a content item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaptionTrack {
    pub content_id: String,
    pub language: String,
    pub captions: Vec<Caption>,
    /// Whether this is auto-generated or human-verified
    pub source: CaptionSource,
}

/// Origin of caption data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CaptionSource {
    Human,
    AutoGenerated,
    MachineTranslated,
}

/// Content accessibility score.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccessibilityScore {
    pub content_id: String,
    /// Does this content have captions?
    pub has_captions: bool,
    /// Number of caption languages available
    pub caption_languages: usize,
    /// Does this content have audio descriptions?
    pub has_audio_description: bool,
    /// Reading level of captions (Flesch-Kincaid grade level, 0-18)
    pub reading_level: f64,
    /// Photosensitive epilepsy risk (flash frequency analysis)
    pub epilepsy_risk: EpilepsyRisk,
    /// Overall accessibility grade (A-F)
    pub grade: AccessibilityGrade,
}

/// Photosensitive epilepsy risk level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EpilepsyRisk {
    /// Safe: no rapid flashing detected
    Safe,
    /// Caution: some rapid transitions
    Caution,
    /// Warning: exceeds ITU-R BT.1702 flash thresholds
    Warning,
}

/// Overall accessibility grade.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum AccessibilityGrade {
    A, // Fully accessible
    B, // Mostly accessible
    C, // Partially accessible
    D, // Minimally accessible
    F, // Not accessible
}

/// Caption store: indexed captions with full-text search and time alignment.
pub struct CaptionStore {
    /// Content ID → caption tracks by language
    pub(crate) tracks: HashMap<String, Vec<CaptionTrack>>,
}

impl CaptionStore {
    pub fn new() -> Self {
        Self {
            tracks: HashMap::new(),
        }
    }

    /// Add a caption track for a content item.
    pub fn add_track(&mut self, track: CaptionTrack) {
        self.tracks
            .entry(track.content_id.clone())
            .or_default()
            .push(track);
    }

    /// Search captions by text across all content.
    /// Returns (content_id, matching captions) pairs.
    pub fn search(&self, query: &str) -> Vec<(String, Vec<&Caption>)> {
        let query_lower = query.to_lowercase();
        let terms: Vec<&str> = query_lower.split_whitespace().collect();

        self.tracks
            .iter()
            .filter_map(|(content_id, tracks)| {
                let matches: Vec<&Caption> = tracks
                    .iter()
                    .flat_map(|t| t.captions.iter())
                    .filter(|c| {
                        let lower = c.text.to_lowercase();
                        terms.iter().all(|term| lower.contains(term))
                    })
                    .collect();

                if matches.is_empty() {
                    None
                } else {
                    Some((content_id.clone(), matches))
                }
            })
            .collect()
    }

    /// Get captions at a specific timestamp.
    pub fn at_time(&self, content_id: &str, timestamp_ms: u64, language: &str) -> Vec<&Caption> {
        self.tracks
            .get(content_id)
            .map(|tracks| {
                tracks
                    .iter()
                    .filter(|t| t.language == language)
                    .flat_map(|t| {
                        t.captions
                            .iter()
                            .filter(|c| timestamp_ms >= c.start_ms && timestamp_ms < c.end_ms)
                    })
                    .collect()
            })
            .unwrap_or_default()
    }

    /// Get all available languages for a content item.
    pub fn languages(&self, content_id: &str) -> Vec<String> {
        self.tracks
            .get(content_id)
            .map(|tracks| tracks.iter().map(|t| t.language.clone()).collect())
            .unwrap_or_default()
    }

    /// Number of content items with captions.
    pub fn content_count(&self) -> usize {
        self.tracks.len()
    }
}

impl Default for CaptionStore {
    fn default() -> Self {
        Self::new()
    }
}

/// Compute accessibility score for a content item.
pub fn compute_accessibility_score(
    content_id: &str,
    caption_store: &CaptionStore,
    has_audio_description: bool,
    flicker_metric: Option<f64>,
) -> AccessibilityScore {
    let languages = caption_store.languages(content_id);
    let has_captions = !languages.is_empty();

    // Estimate reading level from caption text
    let reading_level = caption_store
        .tracks
        .get(content_id)
        .and_then(|tracks| tracks.first())
        .map(|track| estimate_reading_level(&track.captions))
        .unwrap_or(0.0);

    // Epilepsy risk from flicker metric
    let epilepsy_risk = match flicker_metric {
        Some(f) if f > 3.0 => EpilepsyRisk::Warning,  // >3 flashes/sec = ITU threshold
        Some(f) if f > 1.0 => EpilepsyRisk::Caution,
        Some(_) => EpilepsyRisk::Safe,
        None => EpilepsyRisk::Safe,
    };

    // Grade calculation
    let mut score = 0u32;
    if has_captions { score += 30; }
    if languages.len() > 1 { score += 10; }
    if has_audio_description { score += 30; }
    if epilepsy_risk == EpilepsyRisk::Safe { score += 15; }
    if reading_level < 8.0 { score += 15; } // Below 8th grade level

    let grade = match score {
        80..=100 => AccessibilityGrade::A,
        60..=79 => AccessibilityGrade::B,
        40..=59 => AccessibilityGrade::C,
        20..=39 => AccessibilityGrade::D,
        _ => AccessibilityGrade::F,
    };

    AccessibilityScore {
        content_id: content_id.to_string(),
        has_captions,
        caption_languages: languages.len(),
        has_audio_description,
        reading_level,
        epilepsy_risk,
        grade,
    }
}

/// Estimate Flesch-Kincaid reading level from captions.
fn estimate_reading_level(captions: &[Caption]) -> f64 {
    if captions.is_empty() {
        return 0.0;
    }

    let all_text: String = captions.iter().map(|c| c.text.as_str()).collect::<Vec<_>>().join(" ");
    let words: Vec<&str> = all_text.split_whitespace().collect();
    let sentences = all_text.matches('.').count()
        + all_text.matches('!').count()
        + all_text.matches('?').count();

    if words.is_empty() || sentences == 0 {
        return 0.0;
    }

    let avg_word_length: f64 = words.iter().map(|w| w.len() as f64).sum::<f64>() / words.len() as f64;
    let avg_sentence_length = words.len() as f64 / sentences as f64;

    // Simplified Flesch-Kincaid: 0.39 * ASL + 11.8 * ASW - 15.59
    // Using avg word length as syllable proxy
    let syllables_per_word = avg_word_length / 3.0; // Rough estimate
    (0.39 * avg_sentence_length + 11.8 * syllables_per_word - 15.59).max(0.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_caption_search() {
        let mut store = CaptionStore::new();
        store.add_track(CaptionTrack {
            content_id: "movie_1".into(),
            language: "en".into(),
            captions: vec![
                Caption { start_ms: 0, end_ms: 3000, text: "Hello world".into(), speaker: None, language: "en".into() },
                Caption { start_ms: 3000, end_ms: 6000, text: "The rain falls softly".into(), speaker: None, language: "en".into() },
            ],
            source: CaptionSource::Human,
        });

        let results = store.search("rain");
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].0, "movie_1");
        assert_eq!(results[0].1.len(), 1);
    }

    #[test]
    fn test_caption_at_time() {
        let mut store = CaptionStore::new();
        store.add_track(CaptionTrack {
            content_id: "movie_1".into(),
            language: "en".into(),
            captions: vec![
                Caption { start_ms: 0, end_ms: 3000, text: "First".into(), speaker: None, language: "en".into() },
                Caption { start_ms: 3000, end_ms: 6000, text: "Second".into(), speaker: None, language: "en".into() },
            ],
            source: CaptionSource::Human,
        });

        let at_1s = store.at_time("movie_1", 1000, "en");
        assert_eq!(at_1s.len(), 1);
        assert_eq!(at_1s[0].text, "First");

        let at_4s = store.at_time("movie_1", 4000, "en");
        assert_eq!(at_4s[0].text, "Second");
    }

    #[test]
    fn test_accessibility_scoring() {
        let mut store = CaptionStore::new();
        store.add_track(CaptionTrack {
            content_id: "movie_1".into(),
            language: "en".into(),
            captions: vec![
                Caption { start_ms: 0, end_ms: 5000, text: "Simple words here. Short sentences.".into(), speaker: None, language: "en".into() },
            ],
            source: CaptionSource::Human,
        });

        let score = compute_accessibility_score("movie_1", &store, true, Some(0.5));
        assert!(score.has_captions);
        assert!(score.has_audio_description);
        assert_eq!(score.epilepsy_risk, EpilepsyRisk::Safe);
        assert!(score.grade <= AccessibilityGrade::B);
    }

    #[test]
    fn test_no_accessibility() {
        let store = CaptionStore::new();
        // Flicker metric > 3.0 = epilepsy warning, so no safe points either
        let score = compute_accessibility_score("movie_none", &store, false, Some(5.0));
        assert!(!score.has_captions);
        assert!(!score.has_audio_description);
        assert_eq!(score.epilepsy_risk, EpilepsyRisk::Warning);
        assert_eq!(score.grade, AccessibilityGrade::F);
    }
}
