//! Cryptographic Attestation — signed energy receipts proving sandbox provenance.
//!
//! Every sandbox instance produces energy receipts. This module adds
//! cryptographic signatures so the launch host can verify:
//!
//! 1. The receipt came from a specific sandbox instance (identity)
//! 2. The receipt data hasn't been tampered with (integrity)
//! 3. The receipt was generated during a specific JWP session (binding)
//!
//! Uses HMAC-SHA256 for symmetric attestation (fast, no key exchange needed)
//! and optionally ECDSA P-256 for asymmetric attestation (third-party verifiable).
//!
//! The attestation key is generated by the launch host and injected into the
//! sandbox at startup via the JWP channel. The sandbox signs every energy
//! receipt with this key. The host verifies on receipt.

use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

/// Attestation key material injected into a sandbox at startup.
#[derive(Debug, Clone)]
pub struct AttestationKey {
    /// Symmetric key for HMAC-SHA256 signing (32 bytes).
    hmac_key: [u8; 32],
    /// Instance ID this key is bound to.
    instance_id: String,
    /// Session nonce (random, unique per session).
    session_nonce: [u8; 16],
}

impl AttestationKey {
    /// Generate a new random attestation key for an instance.
    pub fn generate(instance_id: &str) -> Self {
        let mut hmac_key = [0u8; 32];
        let mut session_nonce = [0u8; 16];
        fill_random(&mut hmac_key);
        fill_random(&mut session_nonce);
        Self {
            hmac_key,
            instance_id: instance_id.to_string(),
            session_nonce,
        }
    }

    /// Create from existing key material (e.g., received via JWP).
    pub fn from_bytes(
        hmac_key: [u8; 32],
        instance_id: String,
        session_nonce: [u8; 16],
    ) -> Self {
        Self {
            hmac_key,
            instance_id,
            session_nonce,
        }
    }

    /// Instance ID this key is bound to.
    pub fn instance_id(&self) -> &str {
        &self.instance_id
    }

    /// Session nonce (hex-encoded).
    pub fn session_nonce_hex(&self) -> String {
        hex_encode(&self.session_nonce)
    }

    /// Serialize key material for transport over JWP.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(48 + self.instance_id.len() + 4);
        out.extend_from_slice(&self.hmac_key);
        out.extend_from_slice(&self.session_nonce);
        let id_bytes = self.instance_id.as_bytes();
        out.extend_from_slice(&(id_bytes.len() as u32).to_be_bytes());
        out.extend_from_slice(id_bytes);
        out
    }

    /// Deserialize key material received over JWP.
    pub fn from_transport_bytes(data: &[u8]) -> Result<Self, AttestationError> {
        if data.len() < 52 {
            return Err(AttestationError::InvalidKeyMaterial(
                "key material too short".into(),
            ));
        }
        let mut hmac_key = [0u8; 32];
        hmac_key.copy_from_slice(&data[..32]);
        let mut session_nonce = [0u8; 16];
        session_nonce.copy_from_slice(&data[32..48]);
        let id_len =
            u32::from_be_bytes([data[48], data[49], data[50], data[51]]) as usize;
        if data.len() < 52 + id_len {
            return Err(AttestationError::InvalidKeyMaterial(
                "truncated instance ID".into(),
            ));
        }
        let instance_id = String::from_utf8(data[52..52 + id_len].to_vec())
            .map_err(|_| AttestationError::InvalidKeyMaterial("invalid UTF-8 in instance ID".into()))?;

        Ok(Self {
            hmac_key,
            instance_id,
            session_nonce,
        })
    }
}

/// A signed energy receipt with cryptographic attestation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignedEnergyReceipt {
    /// Instance that produced this receipt.
    pub instance_id: String,
    /// Session nonce (hex-encoded) binding this receipt to a JWP session.
    pub session_nonce: String,
    /// Sequence number within the session (monotonically increasing).
    pub sequence: u64,
    /// Energy consumed in microjoules.
    pub energy_uj: u64,
    /// Carbon emissions in micro-grams CO2 equivalent.
    pub carbon_ugco2eq: u64,
    /// Timestamp (nanoseconds since epoch).
    pub timestamp_ns: u64,
    /// SHA-256 hash of the receipt payload (before signing).
    pub payload_hash: String,
    /// HMAC-SHA256 signature over the payload hash + session nonce.
    pub signature: String,
}

impl SignedEnergyReceipt {
    /// Verify this receipt against an attestation key.
    pub fn verify(&self, key: &AttestationKey) -> Result<(), AttestationError> {
        // Check instance ID matches
        if self.instance_id != key.instance_id {
            return Err(AttestationError::InstanceMismatch {
                expected: key.instance_id.clone(),
                got: self.instance_id.clone(),
            });
        }

        // Check session nonce matches
        if self.session_nonce != key.session_nonce_hex() {
            return Err(AttestationError::NonceMismatch);
        }

        // Recompute payload hash
        let expected_hash = compute_payload_hash(
            &self.instance_id,
            &self.session_nonce,
            self.sequence,
            self.energy_uj,
            self.carbon_ugco2eq,
            self.timestamp_ns,
        );
        if self.payload_hash != expected_hash {
            return Err(AttestationError::PayloadTampered);
        }

        // Verify HMAC signature
        let expected_sig = compute_signature(&key.hmac_key, &self.payload_hash, &key.session_nonce);
        if self.signature != expected_sig {
            return Err(AttestationError::InvalidSignature);
        }

        Ok(())
    }
}

/// Signs energy receipts inside a sandbox.
pub struct ReceiptSigner {
    key: AttestationKey,
    sequence: u64,
}

impl ReceiptSigner {
    /// Create a new signer with the given key.
    pub fn new(key: AttestationKey) -> Self {
        Self { key, sequence: 0 }
    }

    /// Sign an energy measurement and produce an attested receipt.
    pub fn sign(&mut self, energy_uj: u64, carbon_ugco2eq: u64) -> SignedEnergyReceipt {
        self.sequence += 1;

        let timestamp_ns = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos() as u64;

        let session_nonce = self.key.session_nonce_hex();

        let payload_hash = compute_payload_hash(
            &self.key.instance_id,
            &session_nonce,
            self.sequence,
            energy_uj,
            carbon_ugco2eq,
            timestamp_ns,
        );

        let signature = compute_signature(
            &self.key.hmac_key,
            &payload_hash,
            &self.key.session_nonce,
        );

        SignedEnergyReceipt {
            instance_id: self.key.instance_id.clone(),
            session_nonce,
            sequence: self.sequence,
            energy_uj,
            carbon_ugco2eq,
            timestamp_ns,
            payload_hash,
            signature,
        }
    }

    /// Current sequence number.
    pub fn sequence(&self) -> u64 {
        self.sequence
    }
}

/// Verifies energy receipts on the launch host side.
pub struct ReceiptVerifier {
    key: AttestationKey,
    /// Last verified sequence number (for replay detection).
    last_sequence: u64,
}

impl ReceiptVerifier {
    /// Create a new verifier with the given key.
    pub fn new(key: AttestationKey) -> Self {
        Self {
            key,
            last_sequence: 0,
        }
    }

    /// Verify a receipt: checks signature, nonce, and sequence ordering.
    pub fn verify(&mut self, receipt: &SignedEnergyReceipt) -> Result<(), AttestationError> {
        // Verify cryptographic integrity
        receipt.verify(&self.key)?;

        // Check sequence ordering (must be monotonically increasing)
        if receipt.sequence <= self.last_sequence {
            return Err(AttestationError::ReplayDetected {
                expected_min: self.last_sequence + 1,
                got: receipt.sequence,
            });
        }

        self.last_sequence = receipt.sequence;
        Ok(())
    }

    /// Last verified sequence number.
    pub fn last_sequence(&self) -> u64 {
        self.last_sequence
    }
}

/// Attestation errors.
#[derive(Debug, thiserror::Error)]
pub enum AttestationError {
    #[error("invalid key material: {0}")]
    InvalidKeyMaterial(String),

    #[error("instance mismatch: expected {expected}, got {got}")]
    InstanceMismatch { expected: String, got: String },

    #[error("session nonce mismatch")]
    NonceMismatch,

    #[error("payload hash mismatch — data tampered")]
    PayloadTampered,

    #[error("invalid HMAC signature")]
    InvalidSignature,

    #[error("replay detected: expected sequence >= {expected_min}, got {got}")]
    ReplayDetected { expected_min: u64, got: u64 },
}

// --- Internal helpers ---

fn compute_payload_hash(
    instance_id: &str,
    session_nonce: &str,
    sequence: u64,
    energy_uj: u64,
    carbon_ugco2eq: u64,
    timestamp_ns: u64,
) -> String {
    let mut hasher = Sha256::new();
    hasher.update(instance_id.as_bytes());
    hasher.update(session_nonce.as_bytes());
    hasher.update(sequence.to_le_bytes());
    hasher.update(energy_uj.to_le_bytes());
    hasher.update(carbon_ugco2eq.to_le_bytes());
    hasher.update(timestamp_ns.to_le_bytes());
    format!("sha256:{:x}", hasher.finalize())
}

fn compute_signature(hmac_key: &[u8; 32], payload_hash: &str, session_nonce: &[u8; 16]) -> String {
    let mut mac = HmacSha256::new_from_slice(hmac_key).expect("HMAC key length is always 32");
    mac.update(payload_hash.as_bytes());
    mac.update(session_nonce);
    format!("hmac256:{:x}", mac.finalize().into_bytes())
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

fn fill_random(buf: &mut [u8]) {
    // Timestamp + thread-seeded PRNG + monotonic counter. Sufficient for
    // session nonces (not long-term secrets). Upgrade to getrandom for
    // production HSM use.
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let mut hasher = DefaultHasher::new();
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos()
        .hash(&mut hasher);
    std::thread::current().id().hash(&mut hasher);
    // Monotonic counter breaks ties when two calls land in the same nanosecond
    COUNTER.fetch_add(1, Ordering::Relaxed).hash(&mut hasher);
    // Mix in address of buf for additional entropy
    (buf.as_ptr() as usize).hash(&mut hasher);
    let mut seed = hasher.finish();
    for byte in buf.iter_mut() {
        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        *byte = (seed >> 33) as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_attestation_key_generate() {
        let key = AttestationKey::generate("test-instance");
        assert_eq!(key.instance_id(), "test-instance");
        assert_eq!(key.session_nonce_hex().len(), 32); // 16 bytes = 32 hex chars
    }

    #[test]
    fn test_attestation_key_roundtrip() {
        let key = AttestationKey::generate("roundtrip-test");
        let bytes = key.to_bytes();
        let restored = AttestationKey::from_transport_bytes(&bytes).unwrap();
        assert_eq!(restored.instance_id(), key.instance_id());
        assert_eq!(restored.session_nonce_hex(), key.session_nonce_hex());
    }

    #[test]
    fn test_attestation_key_from_bytes_too_short() {
        let result = AttestationKey::from_transport_bytes(&[0u8; 10]);
        assert!(result.is_err());
    }

    #[test]
    fn test_sign_and_verify() {
        let key = AttestationKey::generate("sign-verify-1");
        let mut signer = ReceiptSigner::new(key.clone());
        let mut verifier = ReceiptVerifier::new(key);

        let receipt = signer.sign(42_000_000, 9_800);
        assert_eq!(receipt.sequence, 1);
        assert_eq!(receipt.energy_uj, 42_000_000);

        verifier.verify(&receipt).unwrap();
        assert_eq!(verifier.last_sequence(), 1);
    }

    #[test]
    fn test_multiple_receipts() {
        let key = AttestationKey::generate("multi-1");
        let mut signer = ReceiptSigner::new(key.clone());
        let mut verifier = ReceiptVerifier::new(key);

        for i in 1..=10 {
            let receipt = signer.sign(i * 1_000_000, i * 233);
            verifier.verify(&receipt).unwrap();
            assert_eq!(verifier.last_sequence(), i);
        }
    }

    #[test]
    fn test_replay_detection() {
        let key = AttestationKey::generate("replay-1");
        let mut signer = ReceiptSigner::new(key.clone());
        let mut verifier = ReceiptVerifier::new(key);

        let r1 = signer.sign(1_000_000, 233);
        let r2 = signer.sign(2_000_000, 466);

        verifier.verify(&r1).unwrap();
        verifier.verify(&r2).unwrap();

        // Replay r1 — should fail
        let err = verifier.verify(&r1).unwrap_err();
        assert!(matches!(err, AttestationError::ReplayDetected { .. }));
    }

    #[test]
    fn test_tampered_energy() {
        let key = AttestationKey::generate("tamper-1");
        let mut signer = ReceiptSigner::new(key.clone());

        let mut receipt = signer.sign(42_000_000, 9_800);
        receipt.energy_uj = 1; // tamper

        let err = receipt.verify(&key).unwrap_err();
        assert!(matches!(err, AttestationError::PayloadTampered));
    }

    #[test]
    fn test_wrong_key() {
        let key1 = AttestationKey::generate("key1");
        let key2 = AttestationKey::generate("key1"); // same instance_id, different key

        let mut signer = ReceiptSigner::new(key1);
        let receipt = signer.sign(1_000_000, 233);

        // Different HMAC key → signature mismatch (or nonce mismatch)
        let err = receipt.verify(&key2).unwrap_err();
        assert!(matches!(
            err,
            AttestationError::NonceMismatch | AttestationError::InvalidSignature
        ));
    }

    #[test]
    fn test_instance_mismatch() {
        let key = AttestationKey::generate("correct-id");
        let wrong_key = AttestationKey::from_bytes(
            key.hmac_key,
            "wrong-id".to_string(),
            key.session_nonce,
        );

        let mut signer = ReceiptSigner::new(key);
        let receipt = signer.sign(1_000_000, 233);

        let err = receipt.verify(&wrong_key).unwrap_err();
        assert!(matches!(err, AttestationError::InstanceMismatch { .. }));
    }

    #[test]
    fn test_receipt_serde() {
        let key = AttestationKey::generate("serde-1");
        let mut signer = ReceiptSigner::new(key.clone());
        let receipt = signer.sign(5_000_000, 1_165);

        let json = serde_json::to_string(&receipt).unwrap();
        let parsed: SignedEnergyReceipt = serde_json::from_str(&json).unwrap();

        parsed.verify(&key).unwrap();
    }

    #[test]
    fn test_hex_encode() {
        assert_eq!(hex_encode(&[0xde, 0xad, 0xbe, 0xef]), "deadbeef");
        assert_eq!(hex_encode(&[0x00, 0xff]), "00ff");
    }
}
